config:
  bns-infra:cloudProvider: azure
  bns-infra:region: westeurope
  bns-infra:nodeCount: "3"
  bns-infra:vmSize: Standard_D2s_v3
  bns-infra:imageRegistry: ghcr.io/yvan2xero/bns-v2
  bns-infra:imageTag: latest
  bns-infra:domain: buynsellem.com
  bns-infra:acmeEmail: your@email.com
  bns-infra:googleClientId: ""
  bns-infra:novuAppIdentifier: ""
  bns-infra:stripePublishableKey: ""
  bns-infra:notchpayPublicKey: ""
  # Secrets — set with: pulumi config set --secret <key> <value> --stack azure-prod
