import type { File } from "payload";
import type { CategoryListingFormConfig } from "../lib/listingFormPreset";

/**
 * The category tree, with the shape of the ad form each category asks for.
 *
 * Two things are configured here, side by side:
 *
 *   - `listingForm` — how the two built-in fields (price, condition) behave.
 *     Settings are inherited down the tree, so a category only carries one when
 *     it genuinely differs from its parent. A flat is never "like new"; a
 *     holiday let is priced per night, not sold; a job offer has a salary, not
 *     a price.
 *   - `attributes` — the questions specific to this category. These are **not**
 *     inherited: a category shows its own array and nothing else, so every
 *     category a seller can pick carries a complete list. Parents keep a short
 *     generic set for the seller who stops at "Vehicles" without going deeper.
 *
 * `condition` is deliberately absent from every attribute list: it is a
 * built-in listing field driven by `listingForm.condition`, and a category
 * attribute of the same name would render a second, competing dropdown.
 *
 * Attribute slugs are the join key for search: `filterable` attributes are
 * pushed to Meilisearch under their slug (see `hooks/meilisearch.ts`), so they
 * are stable, lowercase and hyphenated, never renamed casually.
 */

export interface CategoryAttributeSeed {
	name: string;
	slug: string;
	type: "text" | "number" | "select" | "boolean" | "date";
	required: boolean;
	filterable: boolean;
	options?: { value: string }[];
	/** Suffix rendered after the value, e.g. "km", "m²". Numbers mostly. */
	unit?: string;
	/** Section heading; attributes sharing one are shown together. */
	group?: string;
	/** Inclusive bounds. Number attributes only — ignored elsewhere. */
	min?: number;
	max?: number;
}

interface CategoryData {
	name: string;
	slug: string;
	description: string;
	icon?: string;
	imageUrl?: string;
	/** Omitted when the category is happy to inherit its parent's form. */
	listingForm?: CategoryListingFormConfig;
	attributes: CategoryAttributeSeed[];
	parent?: string;
}

/** Shorthand for the `options` array a `select` attribute needs. */
const choices = (...values: string[]): { value: string }[] =>
	values.map((value) => ({ value }));

/**
 * Reused verbatim in several places. Kept as constants so the same question is
 * asked with the same words — and the same stored values — wherever it appears.
 */
const YES_NO_GROUP_EQUIPMENT = "Equipment";
const COLORS = choices(
	"Black",
	"White",
	"Silver",
	"Grey",
	"Red",
	"Blue",
	"Green",
	"Beige",
	"Brown",
	"Yellow",
	"Other",
);

const categoryDefinitions: CategoryData[] = [
	// ─── Top-level: Vehicles ───
	{
		name: "Vehicles",
		slug: "vehicles",
		description: "Cars, motorcycles, trucks, and other vehicles",
		icon: "car",
		imageUrl:
			"https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&h=600&fit=crop",
		// Goods sold outright: a price is expected and wear matters.
		listingForm: { type: "product" },
		attributes: [
			{
				name: "Vehicle Type",
				slug: "vehicle-type",
				type: "select",
				required: true,
				filterable: true,
				options: choices(
					"Car",
					"Motorcycle",
					"Scooter",
					"Van",
					"Pickup",
					"Truck",
					"Bus",
					"Trailer",
					"Spare Parts",
					"Other",
				),
			},
			{
				name: "Brand",
				slug: "brand",
				type: "text",
				required: false,
				filterable: true,
			},
			{
				name: "Year",
				slug: "year",
				type: "number",
				required: false,
				filterable: true,
				min: 1950,
				max: 2030,
			},
			{
				name: "Mileage",
				slug: "mileage",
				type: "number",
				required: false,
				filterable: true,
				unit: "km",
				min: 0,
				max: 2000000,
			},
			{
				name: "Fuel Type",
				slug: "fuel-type",
				type: "select",
				required: false,
				filterable: true,
				options: choices("Petrol", "Diesel", "Electric", "Hybrid", "LPG"),
			},
		],
	},
	{
		name: "Cars",
		slug: "cars",
		description: "Used and new cars for sale",
		icon: "car-front",
		imageUrl:
			"https://images.unsplash.com/photo-1549924231-f129b911e442?w=800&h=600&fit=crop",
		parent: "vehicles",
		attributes: [
			{
				name: "Brand",
				slug: "brand",
				type: "select",
				required: true,
				filterable: true,
				group: "Vehicle",
				options: choices(
					"Toyota",
					"Honda",
					"BMW",
					"Mercedes",
					"Ford",
					"Volkswagen",
					"Audi",
					"Peugeot",
					"Renault",
					"Hyundai",
					"Kia",
					"Nissan",
					"Mitsubishi",
					"Suzuki",
					"Land Rover",
					"Other",
				),
			},
			{
				name: "Model",
				slug: "model",
				type: "text",
				required: true,
				filterable: false,
				group: "Vehicle",
			},
			{
				name: "Version / Trim",
				slug: "trim",
				type: "text",
				required: false,
				filterable: false,
				group: "Vehicle",
			},
			{
				name: "Body Type",
				slug: "body-type",
				type: "select",
				required: false,
				filterable: true,
				group: "Vehicle",
				options: choices(
					"Sedan",
					"Hatchback",
					"SUV / Crossover",
					"Estate",
					"Coupé",
					"Convertible",
					"Minivan",
					"Pickup",
					"Van",
				),
			},
			{
				name: "Year",
				slug: "year",
				type: "number",
				required: true,
				filterable: true,
				group: "Vehicle",
				min: 1950,
				max: 2030,
			},
			{
				name: "First Registration",
				slug: "first-registration",
				type: "date",
				required: false,
				filterable: false,
				group: "Vehicle",
			},
			{
				name: "Mileage",
				slug: "mileage",
				type: "number",
				required: true,
				filterable: true,
				group: "Vehicle",
				unit: "km",
				min: 0,
				max: 1000000,
			},
			{
				name: "Fuel Type",
				slug: "fuel-type",
				type: "select",
				required: true,
				filterable: true,
				group: "Engine & Performance",
				options: choices(
					"Petrol",
					"Diesel",
					"Electric",
					"Hybrid",
					"Plug-in Hybrid",
					"LPG",
				),
			},
			{
				name: "Transmission",
				slug: "transmission",
				type: "select",
				required: true,
				filterable: true,
				group: "Engine & Performance",
				options: choices("Automatic", "Manual", "Semi-automatic"),
			},
			{
				name: "Engine Size",
				slug: "engine-size",
				type: "number",
				required: false,
				filterable: true,
				group: "Engine & Performance",
				unit: "cm³",
				min: 50,
				max: 10000,
			},
			{
				name: "Power",
				slug: "power",
				type: "number",
				required: false,
				filterable: true,
				group: "Engine & Performance",
				unit: "hp",
				min: 1,
				max: 2000,
			},
			{
				name: "Doors",
				slug: "doors",
				type: "select",
				required: false,
				filterable: true,
				group: "Body & Interior",
				options: choices("2", "3", "4", "5"),
			},
			{
				name: "Seats",
				slug: "seats",
				type: "number",
				required: false,
				filterable: true,
				group: "Body & Interior",
				min: 1,
				max: 9,
			},
			{
				name: "Colour",
				slug: "color",
				type: "select",
				required: false,
				filterable: true,
				group: "Body & Interior",
				options: COLORS,
			},
			{
				name: "Air Conditioning",
				slug: "air-conditioning",
				type: "select",
				required: false,
				filterable: true,
				group: YES_NO_GROUP_EQUIPMENT,
				options: choices("None", "Manual", "Automatic"),
			},
			{
				name: "Navigation System",
				slug: "gps",
				type: "boolean",
				required: false,
				filterable: false,
				group: YES_NO_GROUP_EQUIPMENT,
			},
			{
				name: "Parking Sensors",
				slug: "parking-sensors",
				type: "boolean",
				required: false,
				filterable: false,
				group: YES_NO_GROUP_EQUIPMENT,
			},
			{
				name: "Sunroof",
				slug: "sunroof",
				type: "boolean",
				required: false,
				filterable: false,
				group: YES_NO_GROUP_EQUIPMENT,
			},
			{
				name: "Previous Owners",
				slug: "owners",
				type: "number",
				required: false,
				filterable: false,
				group: "History & Paperwork",
				min: 1,
				max: 20,
			},
			{
				name: "Full Service History",
				slug: "service-history",
				type: "boolean",
				required: false,
				filterable: true,
				group: "History & Paperwork",
			},
			{
				name: "Accident-free",
				slug: "accident-free",
				type: "boolean",
				required: false,
				filterable: true,
				group: "History & Paperwork",
			},
			{
				name: "Technical Inspection Valid Until",
				slug: "technical-inspection",
				type: "date",
				required: false,
				filterable: false,
				group: "History & Paperwork",
			},
			{
				name: "Under Warranty",
				slug: "warranty",
				type: "boolean",
				required: false,
				filterable: true,
				group: "History & Paperwork",
			},
		],
	},
	{
		name: "Motorcycles",
		slug: "motorcycles",
		description: "Motorcycles, scooters, and ATVs",
		icon: "bike",
		imageUrl:
			"https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&h=600&fit=crop",
		parent: "vehicles",
		attributes: [
			{
				name: "Brand",
				slug: "brand",
				type: "select",
				required: true,
				filterable: true,
				group: "Vehicle",
				options: choices(
					"Yamaha",
					"Honda",
					"Kawasaki",
					"Suzuki",
					"BMW",
					"Ducati",
					"KTM",
					"Harley-Davidson",
					"Royal Enfield",
					"Bajaj",
					"TVS",
					"Other",
				),
			},
			{
				name: "Model",
				slug: "model",
				type: "text",
				required: true,
				filterable: false,
				group: "Vehicle",
			},
			{
				name: "Motorcycle Type",
				slug: "moto-type",
				type: "select",
				required: true,
				filterable: true,
				group: "Vehicle",
				options: choices(
					"Roadster",
					"Sport",
					"Trail / Adventure",
					"Cruiser",
					"Touring",
					"Scooter",
					"Enduro / Cross",
					"ATV / Quad",
					"Custom",
				),
			},
			{
				name: "Year",
				slug: "year",
				type: "number",
				required: true,
				filterable: true,
				group: "Vehicle",
				min: 1950,
				max: 2030,
			},
			{
				name: "Mileage",
				slug: "mileage",
				type: "number",
				required: false,
				filterable: true,
				group: "Vehicle",
				unit: "km",
				min: 0,
				max: 500000,
			},
			{
				name: "Engine Size",
				slug: "engine-size",
				type: "number",
				required: true,
				filterable: true,
				group: "Engine & Performance",
				unit: "cm³",
				min: 49,
				max: 3000,
			},
			{
				name: "Power",
				slug: "power",
				type: "number",
				required: false,
				filterable: true,
				group: "Engine & Performance",
				unit: "hp",
				min: 1,
				max: 400,
			},
			{
				name: "Cooling",
				slug: "cooling",
				type: "select",
				required: false,
				filterable: false,
				group: "Engine & Performance",
				options: choices("Air", "Liquid", "Oil"),
			},
			{
				name: "Licence Required",
				slug: "licence",
				type: "select",
				required: false,
				filterable: true,
				group: "Engine & Performance",
				options: choices("A1", "A2", "A", "B", "None"),
			},
			{
				name: "Colour",
				slug: "color",
				type: "select",
				required: false,
				filterable: true,
				group: "Appearance",
				options: COLORS,
			},
			{
				name: "ABS",
				slug: "abs",
				type: "boolean",
				required: false,
				filterable: true,
				group: YES_NO_GROUP_EQUIPMENT,
			},
			{
				name: "Top Case / Luggage",
				slug: "luggage",
				type: "boolean",
				required: false,
				filterable: false,
				group: YES_NO_GROUP_EQUIPMENT,
			},
			{
				name: "Papers in Order",
				slug: "papers-ok",
				type: "boolean",
				required: false,
				filterable: true,
				group: "History & Paperwork",
			},
			{
				name: "Under Warranty",
				slug: "warranty",
				type: "boolean",
				required: false,
				filterable: true,
				group: "History & Paperwork",
			},
		],
	},
	{
		name: "Trucks & Utility",
		slug: "trucks-utility",
		description: "Trucks, vans, and utility vehicles",
		icon: "truck",
		imageUrl:
			"https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&h=600&fit=crop",
		parent: "vehicles",
		attributes: [
			{
				name: "Type",
				slug: "type",
				type: "select",
				required: true,
				filterable: true,
				group: "Vehicle",
				options: choices(
					"Truck",
					"Van",
					"Pickup",
					"Bus",
					"Tractor Unit",
					"Trailer",
					"Construction Machine",
					"Other",
				),
			},
			{
				name: "Brand",
				slug: "brand",
				type: "text",
				required: true,
				filterable: true,
				group: "Vehicle",
			},
			{
				name: "Model",
				slug: "model",
				type: "text",
				required: false,
				filterable: false,
				group: "Vehicle",
			},
			{
				name: "Year",
				slug: "year",
				type: "number",
				required: true,
				filterable: true,
				group: "Vehicle",
				min: 1950,
				max: 2030,
			},
			{
				name: "Mileage",
				slug: "mileage",
				type: "number",
				required: true,
				filterable: true,
				group: "Vehicle",
				unit: "km",
				min: 0,
				max: 2000000,
			},
			{
				name: "Fuel Type",
				slug: "fuel-type",
				type: "select",
				required: false,
				filterable: true,
				group: "Engine & Performance",
				options: choices("Diesel", "Petrol", "Electric", "Hybrid"),
			},
			{
				name: "Transmission",
				slug: "transmission",
				type: "select",
				required: false,
				filterable: true,
				group: "Engine & Performance",
				options: choices("Manual", "Automatic"),
			},
			{
				name: "Power",
				slug: "power",
				type: "number",
				required: false,
				filterable: true,
				group: "Engine & Performance",
				unit: "hp",
				min: 20,
				max: 1000,
			},
			{
				name: "Payload Capacity",
				slug: "payload-capacity",
				type: "number",
				required: false,
				filterable: true,
				group: "Load",
				unit: "t",
				min: 0,
				max: 60,
			},
			{
				name: "Gross Vehicle Weight",
				slug: "gross-weight",
				type: "number",
				required: false,
				filterable: true,
				group: "Load",
				unit: "t",
				min: 0,
				max: 80,
			},
			{
				name: "Load Volume",
				slug: "load-volume",
				type: "number",
				required: false,
				filterable: false,
				group: "Load",
				unit: "m³",
				min: 0,
				max: 200,
			},
			{
				name: "Axles",
				slug: "axles",
				type: "number",
				required: false,
				filterable: false,
				group: "Load",
				min: 1,
				max: 8,
			},
			{
				name: "Seats",
				slug: "seats",
				type: "number",
				required: false,
				filterable: true,
				group: "Load",
				min: 1,
				max: 90,
			},
			{
				name: "Refrigerated",
				slug: "refrigerated",
				type: "boolean",
				required: false,
				filterable: true,
				group: YES_NO_GROUP_EQUIPMENT,
			},
			{
				name: "Tail Lift",
				slug: "tail-lift",
				type: "boolean",
				required: false,
				filterable: false,
				group: YES_NO_GROUP_EQUIPMENT,
			},
			{
				name: "Technical Inspection Valid Until",
				slug: "technical-inspection",
				type: "date",
				required: false,
				filterable: false,
				group: "History & Paperwork",
			},
		],
	},

	// ─── Top-level: Real Estate ───
	{
		name: "Real Estate",
		slug: "real-estate",
		description: "Properties for sale and rent",
		icon: "home",
		imageUrl:
			"https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop",
		// Property always carries a price — sale price or rent — but asking
		// whether a flat is "like new" is nonsense, so condition is hidden.
		// No priceLabel: the tree mixes sales and lets, and one word cannot
		// serve both. Children may say more.
		listingForm: { type: "rental" },
		attributes: [
			{
				name: "Property Type",
				slug: "property-type",
				type: "select",
				required: true,
				filterable: true,
				options: choices(
					"Apartment",
					"House / Villa",
					"Studio",
					"Room",
					"Office",
					"Shop",
					"Warehouse",
					"Land",
					"Parking / Garage",
					"Other",
				),
			},
			{
				name: "Transaction Type",
				slug: "transaction-type",
				type: "select",
				required: true,
				filterable: true,
				options: choices("Sale", "Rent", "Seasonal Rental"),
			},
			{
				name: "Surface",
				slug: "surface",
				type: "number",
				required: false,
				filterable: true,
				unit: "m²",
				min: 1,
				max: 100000,
			},
			{
				name: "Rooms",
				slug: "rooms",
				type: "number",
				required: false,
				filterable: true,
				min: 1,
				max: 50,
			},
		],
	},
	{
		name: "Apartments",
		slug: "apartments",
		description: "Apartments and flats for sale or rent",
		icon: "building",
		imageUrl:
			"https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
		parent: "real-estate",
		attributes: [
			{
				name: "Transaction Type",
				slug: "transaction-type",
				type: "select",
				required: true,
				filterable: true,
				group: "Property",
				options: choices("Sale", "Rent", "Seasonal Rental"),
			},
			{
				name: "Apartment Type",
				slug: "apartment-type",
				type: "select",
				required: false,
				filterable: true,
				group: "Property",
				options: choices(
					"Studio",
					"Flat",
					"Duplex",
					"Penthouse",
					"Room in Shared Flat",
				),
			},
			{
				name: "Surface",
				slug: "surface",
				type: "number",
				required: true,
				filterable: true,
				group: "Surface & Layout",
				unit: "m²",
				min: 5,
				max: 2000,
			},
			{
				name: "Rooms",
				slug: "rooms",
				type: "number",
				required: true,
				filterable: true,
				group: "Surface & Layout",
				min: 1,
				max: 30,
			},
			{
				name: "Bedrooms",
				slug: "bedrooms",
				type: "number",
				required: true,
				filterable: true,
				group: "Surface & Layout",
				min: 0,
				max: 20,
			},
			{
				name: "Bathrooms",
				slug: "bathrooms",
				type: "number",
				required: true,
				filterable: true,
				group: "Surface & Layout",
				min: 1,
				max: 10,
			},
			{
				name: "Floor",
				slug: "floor",
				type: "number",
				required: false,
				filterable: true,
				group: "Surface & Layout",
				min: 0,
				max: 60,
			},
			{
				name: "Floors in Building",
				slug: "total-floors",
				type: "number",
				required: false,
				filterable: false,
				group: "Surface & Layout",
				min: 1,
				max: 60,
			},
			{
				name: "Year Built",
				slug: "year-built",
				type: "number",
				required: false,
				filterable: false,
				group: "Surface & Layout",
				min: 1900,
				max: 2030,
			},
			{
				name: "Furnished",
				slug: "furnished",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Amenities",
			},
			{
				name: "Elevator",
				slug: "elevator",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Amenities",
			},
			{
				name: "Parking",
				slug: "parking",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Amenities",
			},
			{
				name: "Balcony / Terrace",
				slug: "balcony",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Amenities",
			},
			{
				name: "Air Conditioning",
				slug: "air-conditioning",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Amenities",
			},
			{
				name: "Security / Caretaker",
				slug: "security",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Amenities",
			},
			{
				name: "Backup Generator",
				slug: "backup-power",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Amenities",
			},
			{
				name: "Water Supply",
				slug: "water-supply",
				type: "select",
				required: false,
				filterable: true,
				group: "Amenities",
				options: choices("Mains", "Borehole", "Mains + Borehole", "None"),
			},
			{
				name: "Available From",
				slug: "available-from",
				type: "date",
				required: false,
				filterable: false,
				group: "Rental Terms",
			},
			{
				name: "Deposit",
				slug: "deposit-months",
				type: "number",
				required: false,
				filterable: false,
				group: "Rental Terms",
				unit: "months",
				min: 0,
				max: 12,
			},
		],
	},
	{
		name: "Houses & Villas",
		slug: "houses",
		description: "Houses, villas, and townhouses",
		icon: "house",
		imageUrl:
			"https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop",
		parent: "real-estate",
		attributes: [
			{
				name: "Transaction Type",
				slug: "transaction-type",
				type: "select",
				required: true,
				filterable: true,
				group: "Property",
				options: choices("Sale", "Rent", "Seasonal Rental"),
			},
			{
				name: "House Type",
				slug: "house-type",
				type: "select",
				required: false,
				filterable: true,
				group: "Property",
				options: choices(
					"Villa",
					"Detached House",
					"Townhouse",
					"Bungalow",
					"Duplex",
					"Farmhouse",
				),
			},
			{
				name: "Surface",
				slug: "surface",
				type: "number",
				required: true,
				filterable: true,
				group: "Surface & Layout",
				unit: "m²",
				min: 10,
				max: 5000,
			},
			{
				name: "Land Area",
				slug: "land-area",
				type: "number",
				required: false,
				filterable: true,
				group: "Surface & Layout",
				unit: "m²",
				min: 10,
				max: 500000,
			},
			{
				name: "Rooms",
				slug: "rooms",
				type: "number",
				required: true,
				filterable: true,
				group: "Surface & Layout",
				min: 1,
				max: 40,
			},
			{
				name: "Bedrooms",
				slug: "bedrooms",
				type: "number",
				required: true,
				filterable: true,
				group: "Surface & Layout",
				min: 0,
				max: 25,
			},
			{
				name: "Bathrooms",
				slug: "bathrooms",
				type: "number",
				required: true,
				filterable: true,
				group: "Surface & Layout",
				min: 1,
				max: 15,
			},
			{
				name: "Levels",
				slug: "levels",
				type: "number",
				required: false,
				filterable: false,
				group: "Surface & Layout",
				min: 1,
				max: 6,
			},
			{
				name: "Year Built",
				slug: "year-built",
				type: "number",
				required: false,
				filterable: false,
				group: "Surface & Layout",
				min: 1900,
				max: 2030,
			},
			{
				name: "Furnished",
				slug: "furnished",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Amenities",
			},
			{
				name: "Garage",
				slug: "garage",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Amenities",
			},
			{
				name: "Garden",
				slug: "garden",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Amenities",
			},
			{
				name: "Swimming Pool",
				slug: "pool",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Amenities",
			},
			{
				name: "Fenced Compound",
				slug: "fenced",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Amenities",
			},
			{
				name: "Air Conditioning",
				slug: "air-conditioning",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Amenities",
			},
			{
				name: "Security / Caretaker",
				slug: "security",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Amenities",
			},
			{
				name: "Backup Generator",
				slug: "backup-power",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Amenities",
			},
			{
				name: "Water Supply",
				slug: "water-supply",
				type: "select",
				required: false,
				filterable: true,
				group: "Amenities",
				options: choices("Mains", "Borehole", "Mains + Borehole", "None"),
			},
			{
				name: "Available From",
				slug: "available-from",
				type: "date",
				required: false,
				filterable: false,
				group: "Rental Terms",
			},
			{
				name: "Deposit",
				slug: "deposit-months",
				type: "number",
				required: false,
				filterable: false,
				group: "Rental Terms",
				unit: "months",
				min: 0,
				max: 12,
			},
		],
	},
	{
		name: "Commercial Property",
		slug: "commercial-property",
		description: "Offices, shops, and commercial spaces",
		icon: "store",
		imageUrl:
			"https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop",
		parent: "real-estate",
		attributes: [
			{
				name: "Transaction Type",
				slug: "transaction-type",
				type: "select",
				required: true,
				filterable: true,
				group: "Property",
				options: choices("Sale", "Rent"),
			},
			{
				name: "Property Type",
				slug: "property-type",
				type: "select",
				required: true,
				filterable: true,
				group: "Property",
				options: choices(
					"Office",
					"Shop",
					"Warehouse",
					"Restaurant",
					"Workshop",
					"Hotel",
					"Business Transfer",
					"Other",
				),
			},
			{
				name: "Surface",
				slug: "surface",
				type: "number",
				required: true,
				filterable: true,
				group: "Surface & Layout",
				unit: "m²",
				min: 5,
				max: 50000,
			},
			{
				name: "Storage Surface",
				slug: "storage-surface",
				type: "number",
				required: false,
				filterable: false,
				group: "Surface & Layout",
				unit: "m²",
				min: 0,
				max: 50000,
			},
			{
				name: "Floor",
				slug: "floor",
				type: "number",
				required: false,
				filterable: false,
				group: "Surface & Layout",
				min: 0,
				max: 60,
			},
			{
				name: "Shop Frontage",
				slug: "frontage",
				type: "number",
				required: false,
				filterable: false,
				group: "Surface & Layout",
				unit: "m",
				min: 0,
				max: 500,
			},
			{
				name: "Parking Spaces",
				slug: "parking-spaces",
				type: "number",
				required: false,
				filterable: true,
				group: "Amenities",
				min: 0,
				max: 500,
			},
			{
				name: "Fitted & Ready to Use",
				slug: "fitted",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Amenities",
			},
			{
				name: "Air Conditioning",
				slug: "air-conditioning",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Amenities",
			},
			{
				name: "Power Supply",
				slug: "power-supply",
				type: "select",
				required: false,
				filterable: true,
				group: "Amenities",
				options: choices("Single-phase", "Three-phase", "None"),
			},
			{
				name: "Available From",
				slug: "available-from",
				type: "date",
				required: false,
				filterable: false,
				group: "Rental Terms",
			},
			{
				name: "Deposit",
				slug: "deposit-months",
				type: "number",
				required: false,
				filterable: false,
				group: "Rental Terms",
				unit: "months",
				min: 0,
				max: 12,
			},
		],
	},
	{
		name: "Land",
		slug: "land",
		description: "Agricultural and building land",
		icon: "mountain",
		imageUrl:
			"https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop",
		parent: "real-estate",
		attributes: [
			{
				name: "Transaction Type",
				slug: "transaction-type",
				type: "select",
				required: true,
				filterable: true,
				group: "Plot",
				options: choices("Sale", "Rent"),
			},
			{
				name: "Land Type",
				slug: "land-type",
				type: "select",
				required: true,
				filterable: true,
				group: "Plot",
				options: choices(
					"Building Land",
					"Agricultural",
					"Industrial",
					"Commercial",
					"Forest",
				),
			},
			{
				name: "Area",
				slug: "area",
				type: "number",
				required: true,
				filterable: true,
				group: "Plot",
				unit: "m²",
				min: 10,
				max: 10000000,
			},
			{
				name: "Frontage",
				slug: "frontage",
				type: "number",
				required: false,
				filterable: false,
				group: "Plot",
				unit: "m",
				min: 0,
				max: 5000,
			},
			{
				name: "Title Deed",
				slug: "title-deed",
				type: "select",
				required: true,
				filterable: true,
				group: "Paperwork",
				options: choices(
					"Land Title",
					"Certificate of Occupancy",
					"Customary Deed",
					"Sale Agreement Only",
					"None",
				),
			},
			{
				name: "Surveyed",
				slug: "surveyed",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Paperwork",
			},
			{
				name: "Road Access",
				slug: "road-access",
				type: "select",
				required: false,
				filterable: true,
				group: "Access & Services",
				options: choices("Tarred Road", "Laterite Road", "Track", "None"),
			},
			{
				name: "Electricity on Site",
				slug: "electricity",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Access & Services",
			},
			{
				name: "Water on Site",
				slug: "water",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Access & Services",
			},
			{
				name: "Fenced",
				slug: "fenced",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Access & Services",
			},
		],
	},

	// ─── Top-level: Electronics ───
	{
		name: "Electronics",
		slug: "electronics",
		description: "Phones, computers, TVs, and gadgets",
		icon: "cpu",
		imageUrl:
			"https://images.unsplash.com/photo-1498049794561-7780e7231661?w=800&h=600&fit=crop",
		listingForm: { type: "product" },
		attributes: [
			{
				name: "Item Type",
				slug: "item-type",
				type: "select",
				required: true,
				filterable: true,
				options: choices(
					"Phone",
					"Tablet",
					"Laptop",
					"Desktop",
					"TV",
					"Monitor",
					"Console",
					"Camera",
					"Audio",
					"Accessory",
					"Other",
				),
			},
			{
				name: "Brand",
				slug: "brand",
				type: "text",
				required: false,
				filterable: true,
			},
			{
				name: "Under Warranty",
				slug: "warranty",
				type: "boolean",
				required: false,
				filterable: true,
			},
		],
	},
	{
		name: "Phones & Tablets",
		slug: "phones",
		description: "Mobile phones, smartphones, and tablets",
		icon: "smartphone",
		imageUrl:
			"https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&h=600&fit=crop",
		parent: "electronics",
		attributes: [
			{
				name: "Item Type",
				slug: "item-type",
				type: "select",
				required: true,
				filterable: true,
				group: "Device",
				options: choices(
					"Smartphone",
					"Tablet",
					"Feature Phone",
					"Smartwatch",
					"Accessory",
				),
			},
			{
				name: "Brand",
				slug: "brand",
				type: "select",
				required: true,
				filterable: true,
				group: "Device",
				options: choices(
					"Apple",
					"Samsung",
					"Google",
					"Xiaomi",
					"Huawei",
					"Tecno",
					"Infinix",
					"Itel",
					"OnePlus",
					"Oppo",
					"Nokia",
					"Other",
				),
			},
			{
				name: "Model",
				slug: "model",
				type: "text",
				required: true,
				filterable: false,
				group: "Device",
			},
			{
				name: "Colour",
				slug: "color",
				type: "select",
				required: false,
				filterable: true,
				group: "Device",
				options: COLORS,
			},
			{
				name: "Storage",
				slug: "storage",
				type: "select",
				required: true,
				filterable: true,
				group: "Specifications",
				options: choices(
					"16GB",
					"32GB",
					"64GB",
					"128GB",
					"256GB",
					"512GB",
					"1TB",
				),
			},
			{
				name: "RAM",
				slug: "ram",
				type: "select",
				required: false,
				filterable: true,
				group: "Specifications",
				options: choices("2GB", "3GB", "4GB", "6GB", "8GB", "12GB", "16GB"),
			},
			{
				name: "Screen Size",
				slug: "screen-size",
				type: "number",
				required: false,
				filterable: true,
				group: "Specifications",
				unit: "in",
				min: 3,
				max: 15,
			},
			{
				name: "Network",
				slug: "network",
				type: "select",
				required: false,
				filterable: true,
				group: "Specifications",
				options: choices("3G", "4G", "5G", "Wi-Fi only"),
			},
			{
				name: "Dual SIM",
				slug: "dual-sim",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Specifications",
			},
			{
				name: "Battery Health",
				slug: "battery-health",
				type: "number",
				required: false,
				filterable: false,
				group: "Specifications",
				unit: "%",
				min: 0,
				max: 100,
			},
			{
				name: "SIM Unlocked",
				slug: "unlocked",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Sale Details",
			},
			{
				name: "Original Box & Accessories",
				slug: "boxed",
				type: "boolean",
				required: false,
				filterable: false,
				group: "Sale Details",
			},
			{
				name: "Under Warranty",
				slug: "warranty",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Sale Details",
			},
		],
	},
	{
		name: "Computers",
		slug: "computers",
		description: "Laptops, desktops, and accessories",
		icon: "laptop",
		imageUrl:
			"https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&h=600&fit=crop",
		parent: "electronics",
		attributes: [
			{
				name: "Type",
				slug: "type",
				type: "select",
				required: true,
				filterable: true,
				group: "Device",
				options: choices(
					"Laptop",
					"Desktop",
					"All-in-One",
					"Mini PC",
					"Server",
					"Component",
					"Accessory",
				),
			},
			{
				name: "Brand",
				slug: "brand",
				type: "select",
				required: true,
				filterable: true,
				group: "Device",
				options: choices(
					"Apple",
					"Dell",
					"HP",
					"Lenovo",
					"Asus",
					"Acer",
					"MSI",
					"Toshiba",
					"Custom Build",
					"Other",
				),
			},
			{
				name: "Model",
				slug: "model",
				type: "text",
				required: false,
				filterable: false,
				group: "Device",
			},
			{
				name: "Year",
				slug: "year",
				type: "number",
				required: false,
				filterable: true,
				group: "Device",
				min: 2000,
				max: 2030,
			},
			{
				name: "Processor",
				slug: "processor",
				type: "select",
				required: false,
				filterable: true,
				group: "Specifications",
				options: choices(
					"Intel Core i3",
					"Intel Core i5",
					"Intel Core i7",
					"Intel Core i9",
					"Intel Celeron / Pentium",
					"AMD Ryzen 3",
					"AMD Ryzen 5",
					"AMD Ryzen 7",
					"AMD Ryzen 9",
					"Apple M-series",
					"Other",
				),
			},
			{
				name: "RAM",
				slug: "ram",
				type: "select",
				required: true,
				filterable: true,
				group: "Specifications",
				options: choices("4GB", "8GB", "16GB", "32GB", "64GB", "128GB"),
			},
			{
				name: "Storage",
				slug: "storage",
				type: "select",
				required: false,
				filterable: true,
				group: "Specifications",
				options: choices(
					"128GB SSD",
					"256GB SSD",
					"512GB SSD",
					"1TB SSD",
					"2TB SSD",
					"500GB HDD",
					"1TB HDD",
					"2TB HDD",
				),
			},
			{
				name: "Graphics Card",
				slug: "graphics",
				type: "text",
				required: false,
				filterable: false,
				group: "Specifications",
			},
			{
				name: "Screen Size",
				slug: "screen-size",
				type: "number",
				required: false,
				filterable: true,
				group: "Specifications",
				unit: "in",
				min: 10,
				max: 34,
			},
			{
				name: "Operating System",
				slug: "os",
				type: "select",
				required: false,
				filterable: true,
				group: "Specifications",
				options: choices(
					"Windows 11",
					"Windows 10",
					"macOS",
					"Linux",
					"ChromeOS",
					"None",
				),
			},
			{
				name: "Battery Life",
				slug: "battery-life",
				type: "number",
				required: false,
				filterable: false,
				group: "Specifications",
				unit: "h",
				min: 0,
				max: 24,
			},
			{
				name: "Original Box & Charger",
				slug: "boxed",
				type: "boolean",
				required: false,
				filterable: false,
				group: "Sale Details",
			},
			{
				name: "Under Warranty",
				slug: "warranty",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Sale Details",
			},
		],
	},
	{
		name: "TVs & Monitors",
		slug: "tvs-monitors",
		description: "Televisions, monitors, and screens",
		icon: "monitor",
		imageUrl:
			"https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&h=600&fit=crop",
		parent: "electronics",
		attributes: [
			{
				name: "Item Type",
				slug: "item-type",
				type: "select",
				required: true,
				filterable: true,
				group: "Device",
				options: choices("TV", "Monitor", "Projector", "Screen Accessory"),
			},
			{
				name: "Brand",
				slug: "brand",
				type: "select",
				required: true,
				filterable: true,
				group: "Device",
				options: choices(
					"Samsung",
					"LG",
					"Sony",
					"TCL",
					"Hisense",
					"Philips",
					"Panasonic",
					"Other",
				),
			},
			{
				name: "Screen Size",
				slug: "screen-size",
				type: "number",
				required: true,
				filterable: true,
				group: "Specifications",
				unit: "in",
				min: 10,
				max: 120,
			},
			{
				name: "Resolution",
				slug: "resolution",
				type: "select",
				required: false,
				filterable: true,
				group: "Specifications",
				options: choices("HD", "Full HD", "2K", "4K", "8K"),
			},
			{
				name: "Panel Technology",
				slug: "panel",
				type: "select",
				required: false,
				filterable: true,
				group: "Specifications",
				options: choices("LED", "OLED", "QLED", "LCD", "Plasma"),
			},
			{
				name: "Refresh Rate",
				slug: "refresh-rate",
				type: "number",
				required: false,
				filterable: true,
				group: "Specifications",
				unit: "Hz",
				min: 24,
				max: 360,
			},
			{
				name: "HDMI Ports",
				slug: "hdmi-ports",
				type: "number",
				required: false,
				filterable: false,
				group: "Specifications",
				min: 0,
				max: 8,
			},
			{
				name: "Smart TV",
				slug: "smart-tv",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Specifications",
			},
			{
				name: "Curved Screen",
				slug: "curved",
				type: "boolean",
				required: false,
				filterable: false,
				group: "Specifications",
			},
			{
				name: "Remote & Stand Included",
				slug: "accessories-included",
				type: "boolean",
				required: false,
				filterable: false,
				group: "Sale Details",
			},
			{
				name: "Under Warranty",
				slug: "warranty",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Sale Details",
			},
		],
	},
	{
		name: "Gaming",
		slug: "gaming",
		description: "Consoles, video games, and gaming accessories",
		icon: "gamepad-2",
		imageUrl:
			"https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=800&h=600&fit=crop",
		parent: "electronics",
		attributes: [
			{
				name: "Platform",
				slug: "platform",
				type: "select",
				required: true,
				filterable: true,
				group: "Item",
				options: choices(
					"PlayStation 5",
					"PlayStation 4",
					"Xbox Series X|S",
					"Xbox One",
					"Nintendo Switch",
					"Retro Console",
					"PC",
					"Other",
				),
			},
			{
				name: "Item Type",
				slug: "item-type",
				type: "select",
				required: true,
				filterable: true,
				group: "Item",
				options: choices("Console", "Game", "Accessory", "Bundle"),
			},
			{
				name: "Edition",
				slug: "edition",
				type: "text",
				required: false,
				filterable: false,
				group: "Item",
			},
			{
				name: "Genre",
				slug: "genre",
				type: "select",
				required: false,
				filterable: true,
				group: "Item",
				options: choices(
					"Action / Adventure",
					"Shooter",
					"Sport",
					"Racing",
					"RPG",
					"Strategy",
					"Family / Party",
					"Other",
				),
			},
			{
				name: "Storage",
				slug: "storage",
				type: "select",
				required: false,
				filterable: true,
				group: "Specifications",
				options: choices("500GB", "825GB", "1TB", "2TB", "Digital Edition"),
			},
			{
				name: "Controllers Included",
				slug: "controllers",
				type: "number",
				required: false,
				filterable: false,
				group: "Specifications",
				min: 0,
				max: 4,
			},
			{
				name: "Original Box",
				slug: "boxed",
				type: "boolean",
				required: false,
				filterable: false,
				group: "Sale Details",
			},
			{
				name: "Under Warranty",
				slug: "warranty",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Sale Details",
			},
		],
	},

	// ─── Top-level: Home & Garden ───
	{
		name: "Home & Garden",
		slug: "home-garden",
		description: "Furniture, appliances, and garden equipment",
		icon: "sofa",
		imageUrl:
			"https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=800&h=600&fit=crop",
		listingForm: { type: "product" },
		attributes: [
			{
				name: "Item Type",
				slug: "item-type",
				type: "select",
				required: true,
				filterable: true,
				options: choices(
					"Furniture",
					"Appliance",
					"Decoration",
					"Kitchenware",
					"Bedding",
					"Lighting",
					"Garden",
					"Tools",
					"Other",
				),
			},
			{
				name: "Room",
				slug: "room",
				type: "select",
				required: false,
				filterable: true,
				options: choices(
					"Living Room",
					"Bedroom",
					"Kitchen",
					"Bathroom",
					"Office",
					"Outdoor",
					"Other",
				),
			},
			{
				name: "Delivery Available",
				slug: "delivery-available",
				type: "boolean",
				required: false,
				filterable: true,
			},
		],
	},
	{
		name: "Furniture",
		slug: "furniture",
		description: "Sofas, beds, tables, and chairs",
		icon: "armchair",
		imageUrl:
			"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&h=600&fit=crop",
		parent: "home-garden",
		attributes: [
			{
				name: "Furniture Type",
				slug: "furniture-type",
				type: "select",
				required: true,
				filterable: true,
				group: "Item",
				options: choices(
					"Sofa",
					"Armchair",
					"Bed",
					"Mattress",
					"Table",
					"Chair",
					"Wardrobe",
					"Desk",
					"Shelf",
					"Chest of Drawers",
					"Other",
				),
			},
			{
				name: "Room",
				slug: "room",
				type: "select",
				required: false,
				filterable: true,
				group: "Item",
				options: choices(
					"Living Room",
					"Bedroom",
					"Kitchen",
					"Bathroom",
					"Office",
					"Outdoor",
					"Children's Room",
				),
			},
			{
				name: "Brand",
				slug: "brand",
				type: "text",
				required: false,
				filterable: true,
				group: "Item",
			},
			{
				name: "Material",
				slug: "material",
				type: "select",
				required: false,
				filterable: true,
				group: "Item",
				options: choices(
					"Wood",
					"Metal",
					"Fabric",
					"Leather",
					"Rattan",
					"Plastic",
					"Glass",
					"Marble",
				),
			},
			{
				name: "Colour",
				slug: "color",
				type: "select",
				required: false,
				filterable: true,
				group: "Item",
				options: COLORS,
			},
			{
				name: "Style",
				slug: "style",
				type: "select",
				required: false,
				filterable: true,
				group: "Item",
				options: choices(
					"Modern",
					"Scandinavian",
					"Classic",
					"Industrial",
					"Rustic",
					"Other",
				),
			},
			{
				name: "Width",
				slug: "width",
				type: "number",
				required: false,
				filterable: false,
				group: "Dimensions",
				unit: "cm",
				min: 1,
				max: 1000,
			},
			{
				name: "Height",
				slug: "height",
				type: "number",
				required: false,
				filterable: false,
				group: "Dimensions",
				unit: "cm",
				min: 1,
				max: 1000,
			},
			{
				name: "Depth",
				slug: "depth",
				type: "number",
				required: false,
				filterable: false,
				group: "Dimensions",
				unit: "cm",
				min: 1,
				max: 1000,
			},
			{
				name: "Seats",
				slug: "seats",
				type: "number",
				required: false,
				filterable: true,
				group: "Dimensions",
				min: 1,
				max: 12,
			},
			{
				name: "Assembly Required",
				slug: "assembly-required",
				type: "boolean",
				required: false,
				filterable: false,
				group: "Sale Details",
			},
			{
				name: "Delivery Available",
				slug: "delivery-available",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Sale Details",
			},
		],
	},
	{
		name: "Appliances",
		slug: "appliances",
		description: "Kitchen and household appliances",
		icon: "refrigerator",
		imageUrl:
			"https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=800&h=600&fit=crop",
		parent: "home-garden",
		attributes: [
			{
				name: "Appliance Type",
				slug: "appliance-type",
				type: "select",
				required: true,
				filterable: true,
				group: "Item",
				options: choices(
					"Refrigerator",
					"Freezer",
					"Washing Machine",
					"Dryer",
					"Oven",
					"Cooker / Hob",
					"Dishwasher",
					"Air Conditioner",
					"Fan",
					"Microwave",
					"Vacuum",
					"Water Heater",
					"Generator",
					"Other",
				),
			},
			{
				name: "Brand",
				slug: "brand",
				type: "select",
				required: false,
				filterable: true,
				group: "Item",
				options: choices(
					"Samsung",
					"LG",
					"Bosch",
					"Whirlpool",
					"Beko",
					"Hisense",
					"Nasco",
					"Binatone",
					"Other",
				),
			},
			{
				name: "Year",
				slug: "year",
				type: "number",
				required: false,
				filterable: false,
				group: "Item",
				min: 1990,
				max: 2030,
			},
			{
				name: "Capacity",
				slug: "capacity",
				type: "number",
				required: false,
				filterable: true,
				group: "Specifications",
				unit: "L",
				min: 0,
				max: 1000,
			},
			{
				name: "Load Capacity",
				slug: "load-capacity",
				type: "number",
				required: false,
				filterable: true,
				group: "Specifications",
				unit: "kg",
				min: 1,
				max: 30,
			},
			{
				name: "Power",
				slug: "power",
				type: "number",
				required: false,
				filterable: false,
				group: "Specifications",
				unit: "W",
				min: 1,
				max: 20000,
			},
			{
				name: "Energy Rating",
				slug: "energy-rating",
				type: "select",
				required: false,
				filterable: true,
				group: "Specifications",
				options: choices("A+++", "A++", "A+", "A", "B", "C", "D"),
			},
			{
				name: "Voltage",
				slug: "voltage",
				type: "select",
				required: false,
				filterable: false,
				group: "Specifications",
				options: choices("220V", "110V", "Dual Voltage"),
			},
			{
				name: "Width",
				slug: "width",
				type: "number",
				required: false,
				filterable: false,
				group: "Specifications",
				unit: "cm",
				min: 10,
				max: 300,
			},
			{
				name: "In Working Order",
				slug: "working-order",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Sale Details",
			},
			{
				name: "Delivery Available",
				slug: "delivery-available",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Sale Details",
			},
			{
				name: "Under Warranty",
				slug: "warranty",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Sale Details",
			},
		],
	},
	{
		name: "Garden & DIY",
		slug: "garden-diy",
		description: "Garden tools, plants, and DIY supplies",
		icon: "flower",
		imageUrl:
			"https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=600&fit=crop",
		parent: "home-garden",
		// Plants, cuttings and leftover materials are often given away or
		// negotiated. Inherits "product" from home-garden but must not force a
		// price on the seller.
		listingForm: { price: "optional" },
		attributes: [
			{
				name: "Category",
				slug: "sub-category",
				type: "select",
				required: true,
				filterable: true,
				group: "Item",
				options: choices(
					"Hand Tools",
					"Power Tools",
					"Plants & Seeds",
					"Outdoor Furniture",
					"Lawn Mower",
					"Building Materials",
					"Decoration",
					"Other",
				),
			},
			{
				name: "Brand",
				slug: "brand",
				type: "text",
				required: false,
				filterable: true,
				group: "Item",
			},
			{
				name: "Power Source",
				slug: "power-source",
				type: "select",
				required: false,
				filterable: true,
				group: "Specifications",
				options: choices("Manual", "Electric", "Battery", "Petrol"),
			},
			{
				name: "Power",
				slug: "power",
				type: "number",
				required: false,
				filterable: false,
				group: "Specifications",
				unit: "W",
				min: 1,
				max: 20000,
			},
			{
				name: "Quantity",
				slug: "quantity",
				type: "number",
				required: false,
				filterable: false,
				group: "Sale Details",
				min: 1,
				max: 10000,
			},
			{
				name: "In Working Order",
				slug: "working-order",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Sale Details",
			},
			{
				name: "Delivery Available",
				slug: "delivery-available",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Sale Details",
			},
		],
	},

	// ─── Top-level: Fashion ───
	{
		name: "Fashion & Clothing",
		slug: "fashion",
		description: "Clothing, shoes, and accessories",
		icon: "shirt",
		imageUrl:
			"https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=600&fit=crop",
		listingForm: { type: "product" },
		attributes: [
			{
				name: "Item Type",
				slug: "item-type",
				type: "select",
				required: true,
				filterable: true,
				options: choices(
					"Clothing",
					"Shoes",
					"Bag",
					"Accessory",
					"Watch",
					"Jewelry",
					"Traditional Wear",
				),
			},
			{
				name: "Worn By",
				slug: "gender",
				type: "select",
				required: true,
				filterable: true,
				options: choices("Men", "Women", "Unisex", "Kids"),
			},
			{
				name: "Size",
				slug: "size",
				type: "text",
				required: false,
				filterable: true,
			},
			{
				name: "Brand",
				slug: "brand",
				type: "text",
				required: false,
				filterable: true,
			},
		],
	},
	{
		name: "Men's Clothing",
		slug: "mens-clothing",
		description: "Shirts, pants, jackets, and more for men",
		icon: "shirt",
		imageUrl:
			"https://images.unsplash.com/photo-1507680434567-5739c80be1ac?w=800&h=600&fit=crop",
		parent: "fashion",
		attributes: [
			{
				name: "Clothing Type",
				slug: "clothing-type",
				type: "select",
				required: true,
				filterable: true,
				group: "Item",
				options: choices(
					"T-Shirt",
					"Shirt",
					"Polo",
					"Pants",
					"Jeans",
					"Shorts",
					"Jacket",
					"Coat",
					"Suit",
					"Traditional Wear",
					"Shoes",
					"Bag",
					"Accessory",
					"Other",
				),
			},
			{
				name: "Brand",
				slug: "brand",
				type: "text",
				required: false,
				filterable: true,
				group: "Item",
			},
			{
				name: "Size",
				slug: "size",
				type: "select",
				required: true,
				filterable: true,
				group: "Fit",
				options: choices("XS", "S", "M", "L", "XL", "XXL", "3XL"),
			},
			{
				name: "Shoe Size (EU)",
				slug: "shoe-size",
				type: "number",
				required: false,
				filterable: true,
				group: "Fit",
				min: 35,
				max: 50,
			},
			{
				name: "Fit",
				slug: "fit",
				type: "select",
				required: false,
				filterable: false,
				group: "Fit",
				options: choices("Slim", "Regular", "Loose", "Oversized"),
			},
			{
				name: "Colour",
				slug: "color",
				type: "select",
				required: false,
				filterable: true,
				group: "Details",
				options: COLORS,
			},
			{
				name: "Material",
				slug: "material",
				type: "select",
				required: false,
				filterable: true,
				group: "Details",
				options: choices(
					"Cotton",
					"Wool",
					"Leather",
					"Denim",
					"Polyester",
					"Silk",
					"Linen",
					"Wax / Ankara",
					"Other",
				),
			},
			{
				name: "Season",
				slug: "season",
				type: "select",
				required: false,
				filterable: false,
				group: "Details",
				options: choices("All Season", "Dry Season", "Rainy Season"),
			},
			{
				name: "Sold as a Lot",
				slug: "lot",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Sale Details",
			},
		],
	},
	{
		name: "Women's Clothing",
		slug: "womens-clothing",
		description: "Dresses, tops, pants, and more for women",
		icon: "shirt",
		imageUrl:
			"https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop",
		parent: "fashion",
		attributes: [
			{
				name: "Clothing Type",
				slug: "clothing-type",
				type: "select",
				required: true,
				filterable: true,
				group: "Item",
				options: choices(
					"Dress",
					"Top",
					"Blouse",
					"Pants",
					"Jeans",
					"Skirt",
					"Jacket",
					"Coat",
					"Traditional Wear",
					"Shoes",
					"Bag",
					"Accessory",
					"Other",
				),
			},
			{
				name: "Brand",
				slug: "brand",
				type: "text",
				required: false,
				filterable: true,
				group: "Item",
			},
			{
				name: "Size",
				slug: "size",
				type: "select",
				required: true,
				filterable: true,
				group: "Fit",
				options: choices("XS", "S", "M", "L", "XL", "XXL", "3XL"),
			},
			{
				name: "Shoe Size (EU)",
				slug: "shoe-size",
				type: "number",
				required: false,
				filterable: true,
				group: "Fit",
				min: 33,
				max: 45,
			},
			{
				name: "Fit",
				slug: "fit",
				type: "select",
				required: false,
				filterable: false,
				group: "Fit",
				options: choices("Slim", "Regular", "Loose", "Oversized"),
			},
			{
				name: "Colour",
				slug: "color",
				type: "select",
				required: false,
				filterable: true,
				group: "Details",
				options: COLORS,
			},
			{
				name: "Material",
				slug: "material",
				type: "select",
				required: false,
				filterable: true,
				group: "Details",
				options: choices(
					"Cotton",
					"Wool",
					"Leather",
					"Denim",
					"Polyester",
					"Silk",
					"Linen",
					"Wax / Ankara",
					"Lace",
					"Other",
				),
			},
			{
				name: "Season",
				slug: "season",
				type: "select",
				required: false,
				filterable: false,
				group: "Details",
				options: choices("All Season", "Dry Season", "Rainy Season"),
			},
			{
				name: "Sold as a Lot",
				slug: "lot",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Sale Details",
			},
		],
	},
	{
		name: "Watches & Jewelry",
		slug: "watches-jewelry",
		description: "Watches, rings, necklaces, and bracelets",
		icon: "watch",
		imageUrl:
			"https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800&h=600&fit=crop",
		parent: "fashion",
		attributes: [
			{
				name: "Item Type",
				slug: "item-type",
				type: "select",
				required: true,
				filterable: true,
				group: "Item",
				options: choices(
					"Watch",
					"Smartwatch",
					"Ring",
					"Necklace",
					"Bracelet",
					"Earrings",
					"Set",
					"Other",
				),
			},
			{
				name: "Brand",
				slug: "brand",
				type: "text",
				required: false,
				filterable: true,
				group: "Item",
			},
			{
				name: "Worn By",
				slug: "gender",
				type: "select",
				required: false,
				filterable: true,
				group: "Item",
				options: choices("Men", "Women", "Unisex"),
			},
			{
				name: "Material",
				slug: "material",
				type: "select",
				required: false,
				filterable: true,
				group: "Materials",
				options: choices(
					"Gold",
					"Gold Plated",
					"Silver",
					"Stainless Steel",
					"Titanium",
					"Leather",
					"Beads",
					"Other",
				),
			},
			{
				name: "Gemstone",
				slug: "gemstone",
				type: "select",
				required: false,
				filterable: true,
				group: "Materials",
				options: choices(
					"None",
					"Diamond",
					"Ruby",
					"Sapphire",
					"Emerald",
					"Pearl",
					"Zirconia",
					"Other",
				),
			},
			{
				name: "Gold Purity",
				slug: "carat",
				type: "number",
				required: false,
				filterable: true,
				group: "Materials",
				unit: "K",
				min: 8,
				max: 24,
			},
			{
				name: "Weight",
				slug: "weight",
				type: "number",
				required: false,
				filterable: false,
				group: "Materials",
				unit: "g",
				min: 0,
				max: 5000,
			},
			{
				name: "Movement",
				slug: "movement",
				type: "select",
				required: false,
				filterable: true,
				group: "Watch Details",
				options: choices("Automatic", "Quartz", "Mechanical", "Smart"),
			},
			{
				name: "Case Diameter",
				slug: "case-diameter",
				type: "number",
				required: false,
				filterable: false,
				group: "Watch Details",
				unit: "mm",
				min: 15,
				max: 60,
			},
			{
				name: "Water Resistant",
				slug: "water-resistant",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Watch Details",
			},
			{
				name: "Box & Papers",
				slug: "box-papers",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Sale Details",
			},
			{
				name: "Certificate of Authenticity",
				slug: "certificate",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Sale Details",
			},
		],
	},

	// ─── Top-level: Jobs & Services ───
	{
		name: "Jobs & Services",
		slug: "jobs-services",
		description: "Job offers, freelance services, and professional help",
		icon: "briefcase",
		imageUrl:
			"https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=800&h=600&fit=crop",
		// Work offered or wanted: a rate is useful but often "on quote", so the
		// price is shown and left optional rather than demanded.
		listingForm: { type: "service", priceLabel: "Rate (XAF)" },
		attributes: [
			{
				name: "Listing Type",
				slug: "listing-type",
				type: "select",
				required: true,
				filterable: true,
				options: choices(
					"Job Offer",
					"Job Wanted",
					"Service Offered",
					"Service Wanted",
				),
			},
			{
				name: "Sector",
				slug: "sector",
				type: "select",
				required: false,
				filterable: true,
				options: choices(
					"IT & Tech",
					"Sales",
					"Marketing",
					"Healthcare",
					"Education",
					"Construction",
					"Hospitality",
					"Transport",
					"Agriculture",
					"Home Services",
					"Other",
				),
			},
			{
				name: "Work Location",
				slug: "location-type",
				type: "select",
				required: false,
				filterable: true,
				options: choices("On Site", "Remote", "Hybrid"),
			},
		],
	},
	{
		name: "Job Offers",
		slug: "job-offers",
		description: "Full-time and part-time job opportunities",
		icon: "briefcase",
		imageUrl:
			"https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop",
		parent: "jobs-services",
		// A job is not sold: the "job" preset hides price and condition. The
		// price field is re-enabled as an optional salary, which is how job
		// boards actually work — advertise it or write "negotiable".
		listingForm: {
			type: "job",
			price: "optional",
			priceLabel: "Monthly salary (XAF)",
		},
		attributes: [
			{
				name: "Job Title",
				slug: "job-title",
				type: "text",
				required: true,
				filterable: false,
				group: "Position",
			},
			{
				name: "Company",
				slug: "company",
				type: "text",
				required: false,
				filterable: false,
				group: "Position",
			},
			{
				name: "Industry",
				slug: "industry",
				type: "select",
				required: true,
				filterable: true,
				group: "Position",
				options: choices(
					"IT & Tech",
					"Sales",
					"Marketing",
					"Finance & Accounting",
					"Healthcare",
					"Education",
					"Construction",
					"Hospitality",
					"Transport & Logistics",
					"Agriculture",
					"Public Sector",
					"Other",
				),
			},
			{
				name: "Positions Open",
				slug: "positions",
				type: "number",
				required: false,
				filterable: false,
				group: "Position",
				min: 1,
				max: 100,
			},
			{
				name: "Contract Type",
				slug: "contract-type",
				type: "select",
				required: true,
				filterable: true,
				group: "Contract",
				options: choices(
					"Full-time",
					"Part-time",
					"Freelance",
					"Internship",
					"Temporary",
					"Apprenticeship",
				),
			},
			{
				name: "Work Location",
				slug: "location-type",
				type: "select",
				required: false,
				filterable: true,
				group: "Contract",
				options: choices("On Site", "Remote", "Hybrid"),
			},
			{
				name: "Working Hours",
				slug: "working-hours",
				type: "number",
				required: false,
				filterable: false,
				group: "Contract",
				unit: "h/week",
				min: 1,
				max: 80,
			},
			{
				name: "Start Date",
				slug: "start-date",
				type: "date",
				required: false,
				filterable: false,
				group: "Contract",
			},
			{
				name: "Application Deadline",
				slug: "application-deadline",
				type: "date",
				required: false,
				filterable: false,
				group: "Contract",
			},
			{
				name: "Experience Level",
				slug: "experience-level",
				type: "select",
				required: false,
				filterable: true,
				group: "Requirements",
				options: choices("Entry Level", "Mid Level", "Senior", "Executive"),
			},
			{
				name: "Years of Experience",
				slug: "experience-years",
				type: "number",
				required: false,
				filterable: true,
				group: "Requirements",
				unit: "years",
				min: 0,
				max: 40,
			},
			{
				name: "Education Level",
				slug: "education-level",
				type: "select",
				required: false,
				filterable: true,
				group: "Requirements",
				options: choices(
					"None",
					"Secondary / BEPC",
					"Baccalauréat",
					"BTS / HND",
					"Bachelor",
					"Master",
					"Doctorate",
				),
			},
			{
				name: "Languages",
				slug: "languages",
				type: "select",
				required: false,
				filterable: true,
				group: "Requirements",
				options: choices("French", "English", "Bilingual", "Other"),
			},
			{
				name: "Driving Licence Required",
				slug: "driving-licence",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Requirements",
			},
		],
	},
	{
		name: "Services",
		slug: "services",
		description: "Professional and personal services",
		icon: "wrench",
		imageUrl:
			"https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&h=600&fit=crop",
		parent: "jobs-services",
		attributes: [
			{
				name: "Service Type",
				slug: "service-type",
				type: "select",
				required: true,
				filterable: true,
				group: "Service",
				options: choices(
					"Plumbing",
					"Electrical",
					"Masonry",
					"Painting",
					"Carpentry",
					"Cleaning",
					"Moving",
					"Tutoring",
					"IT Support",
					"Web & Design",
					"Beauty",
					"Catering",
					"Events",
					"Transport",
					"Security",
					"Other",
				),
			},
			{
				name: "Pricing Basis",
				slug: "pricing-basis",
				type: "select",
				required: false,
				filterable: true,
				group: "Service",
				options: choices(
					"Per Hour",
					"Per Day",
					"Per Job",
					"Per Month",
					"On Quote",
				),
			},
			{
				name: "Years of Experience",
				slug: "experience-years",
				type: "number",
				required: false,
				filterable: true,
				group: "Provider",
				unit: "years",
				min: 0,
				max: 50,
			},
			{
				name: "Certified / Licensed",
				slug: "certified",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Provider",
			},
			{
				name: "Work Guaranteed",
				slug: "guarantee",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Provider",
			},
			{
				name: "Areas Covered",
				slug: "service-area",
				type: "text",
				required: false,
				filterable: false,
				group: "Availability",
			},
			{
				name: "Travels to Client",
				slug: "on-site",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Availability",
			},
			{
				name: "Available Weekends",
				slug: "available-weekends",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Availability",
			},
			{
				name: "Emergency / 24-7",
				slug: "emergency",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Availability",
			},
		],
	},

	// ─── Top-level: Leisure ───
	{
		name: "Leisure & Sports",
		slug: "leisure-sports",
		description: "Sports equipment, hobbies, and entertainment",
		icon: "dumbbell",
		imageUrl:
			"https://images.unsplash.com/photo-1461896836934-bd45ba3bdb78?w=800&h=600&fit=crop",
		// Mostly second-hand goods. travel-vacation overrides this below.
		listingForm: { type: "product" },
		attributes: [
			{
				name: "Item Type",
				slug: "item-type",
				type: "select",
				required: true,
				filterable: true,
				options: choices(
					"Sports Equipment",
					"Bicycle",
					"Book",
					"Music",
					"Film",
					"Musical Instrument",
					"Board Game",
					"Collectible",
					"Camping",
					"Other",
				),
			},
			{
				name: "Brand",
				slug: "brand",
				type: "text",
				required: false,
				filterable: true,
			},
		],
	},
	{
		name: "Sports Equipment",
		slug: "sports-equipment",
		description: "Fitness gear, bikes, and sports accessories",
		icon: "dumbbell",
		imageUrl:
			"https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&h=600&fit=crop",
		parent: "leisure-sports",
		attributes: [
			{
				name: "Sport",
				slug: "sport",
				type: "select",
				required: true,
				filterable: true,
				group: "Item",
				options: choices(
					"Football",
					"Basketball",
					"Tennis",
					"Swimming",
					"Cycling",
					"Running",
					"Gym & Fitness",
					"Martial Arts",
					"Camping & Hiking",
					"Fishing",
					"Other",
				),
			},
			{
				name: "Equipment Type",
				slug: "item-type",
				type: "select",
				required: true,
				filterable: true,
				group: "Item",
				options: choices(
					"Bicycle",
					"Fitness Machine",
					"Weights",
					"Racket",
					"Ball",
					"Apparel",
					"Shoes",
					"Protective Gear",
					"Camping Gear",
					"Other",
				),
			},
			{
				name: "Brand",
				slug: "brand",
				type: "text",
				required: false,
				filterable: true,
				group: "Item",
			},
			{
				name: "Worn / Used By",
				slug: "gender",
				type: "select",
				required: false,
				filterable: true,
				group: "Item",
				options: choices("Men", "Women", "Unisex", "Kids"),
			},
			{
				name: "Size",
				slug: "size",
				type: "text",
				required: false,
				filterable: true,
				group: "Specifications",
			},
			{
				name: "Weight",
				slug: "weight",
				type: "number",
				required: false,
				filterable: false,
				group: "Specifications",
				unit: "kg",
				min: 0,
				max: 500,
			},
			{
				name: "Electric / Motorised",
				slug: "electric",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Specifications",
			},
			{
				name: "Delivery Available",
				slug: "delivery-available",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Sale Details",
			},
		],
	},
	{
		name: "Books & Media",
		slug: "books-media",
		description: "Books, music, movies, and collectibles",
		icon: "book-open",
		imageUrl:
			"https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=800&h=600&fit=crop",
		parent: "leisure-sports",
		attributes: [
			{
				name: "Media Type",
				slug: "media-type",
				type: "select",
				required: true,
				filterable: true,
				group: "Item",
				options: choices(
					"Book",
					"Textbook",
					"Comic / Manga",
					"Magazine",
					"Vinyl / CD",
					"DVD / Blu-ray",
					"Musical Instrument",
					"Board Game",
					"Collectible",
					"Other",
				),
			},
			{
				name: "Author / Artist",
				slug: "author",
				type: "text",
				required: false,
				filterable: true,
				group: "Item",
			},
			{
				name: "Genre",
				slug: "genre",
				type: "select",
				required: false,
				filterable: true,
				group: "Item",
				options: choices(
					"Fiction",
					"Non-fiction",
					"Education",
					"Children",
					"Religion",
					"Science",
					"Business",
					"Music",
					"Other",
				),
			},
			{
				name: "Language",
				slug: "language",
				type: "select",
				required: false,
				filterable: true,
				group: "Item",
				options: choices("French", "English", "Bilingual", "Other"),
			},
			{
				name: "Format",
				slug: "format",
				type: "select",
				required: false,
				filterable: true,
				group: "Details",
				options: choices(
					"Paperback",
					"Hardcover",
					"Vinyl",
					"CD",
					"DVD",
					"Blu-ray",
					"Digital",
				),
			},
			{
				name: "Publication Year",
				slug: "publication-year",
				type: "number",
				required: false,
				filterable: false,
				group: "Details",
				min: 1400,
				max: 2030,
			},
			{
				name: "ISBN / Reference",
				slug: "isbn",
				type: "text",
				required: false,
				filterable: false,
				group: "Details",
			},
			{
				name: "Quantity",
				slug: "quantity",
				type: "number",
				required: false,
				filterable: false,
				group: "Sale Details",
				min: 1,
				max: 10000,
			},
			{
				name: "Signed / Collector Edition",
				slug: "collector",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Sale Details",
			},
		],
	},
	{
		name: "Travel & Vacation",
		slug: "travel-vacation",
		description: "Holiday rentals, trips, and luggage",
		icon: "plane",
		imageUrl:
			"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop",
		parent: "leisure-sports",
		// Stays and tickets, not goods: a rate is expected and "is it like new?"
		// is meaningless for a villa. This is the case the old slug whitelist
		// could not express.
		listingForm: { type: "rental", priceLabel: "Rate (XAF)" },
		attributes: [
			{
				name: "Listing Type",
				slug: "listing-type",
				type: "select",
				required: true,
				filterable: true,
				group: "Offer",
				options: choices(
					"Holiday Rental",
					"Guided Tour",
					"Tickets",
					"Travel Equipment",
					"Other",
				),
			},
			{
				name: "Destination",
				slug: "destination",
				type: "text",
				required: false,
				filterable: true,
				group: "Offer",
			},
			{
				name: "Accommodation Type",
				slug: "accommodation-type",
				type: "select",
				required: false,
				filterable: true,
				group: "Stay",
				options: choices(
					"Villa",
					"Apartment",
					"Room",
					"Hotel",
					"Guesthouse",
					"Bungalow",
					"Camping",
				),
			},
			{
				name: "Guests",
				slug: "guests",
				type: "number",
				required: false,
				filterable: true,
				group: "Stay",
				min: 1,
				max: 50,
			},
			{
				name: "Bedrooms",
				slug: "bedrooms",
				type: "number",
				required: false,
				filterable: true,
				group: "Stay",
				min: 0,
				max: 20,
			},
			{
				name: "Minimum Nights",
				slug: "minimum-nights",
				type: "number",
				required: false,
				filterable: false,
				group: "Stay",
				unit: "nights",
				min: 1,
				max: 90,
			},
			{
				name: "Available From",
				slug: "available-from",
				type: "date",
				required: false,
				filterable: false,
				group: "Availability",
			},
			{
				name: "Available Until",
				slug: "available-to",
				type: "date",
				required: false,
				filterable: false,
				group: "Availability",
			},
			{
				name: "Wi-Fi",
				slug: "wifi",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Amenities",
			},
			{
				name: "Air Conditioning",
				slug: "air-conditioning",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Amenities",
			},
			{
				name: "Swimming Pool",
				slug: "pool",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Amenities",
			},
			{
				name: "Parking",
				slug: "parking",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Amenities",
			},
			{
				name: "Breakfast Included",
				slug: "breakfast",
				type: "boolean",
				required: false,
				filterable: false,
				group: "Amenities",
			},
			{
				name: "Pets Allowed",
				slug: "pets-allowed",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Amenities",
			},
		],
	},

	// ─── Top-level: Kids & Baby ───
	{
		name: "Kids & Baby",
		slug: "kids-baby",
		description: "Toys, baby gear, and children's clothing",
		icon: "baby",
		imageUrl:
			"https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&h=600&fit=crop",
		// Second-hand goods where wear genuinely matters to the buyer.
		listingForm: { type: "product" },
		attributes: [
			{
				name: "Category",
				slug: "sub-category",
				type: "select",
				required: true,
				filterable: true,
				group: "Item",
				options: choices(
					"Toys",
					"Baby Gear",
					"Children's Clothing",
					"Stroller",
					"Car Seat",
					"Cot & Bedding",
					"Feeding",
					"School Supplies",
					"Other",
				),
			},
			{
				name: "Age Range",
				slug: "age-range",
				type: "select",
				required: false,
				filterable: true,
				group: "Item",
				options: choices(
					"0-1 year",
					"1-3 years",
					"3-6 years",
					"6-12 years",
					"12+ years",
				),
			},
			{
				name: "For",
				slug: "gender",
				type: "select",
				required: false,
				filterable: true,
				group: "Item",
				options: choices("Boy", "Girl", "Unisex"),
			},
			{
				name: "Brand",
				slug: "brand",
				type: "text",
				required: false,
				filterable: true,
				group: "Item",
			},
			{
				name: "Clothing Size",
				slug: "size",
				type: "text",
				required: false,
				filterable: true,
				group: "Details",
			},
			{
				name: "Quantity",
				slug: "quantity",
				type: "number",
				required: false,
				filterable: false,
				group: "Sale Details",
				min: 1,
				max: 1000,
			},
			{
				name: "Sold as a Lot",
				slug: "lot",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Sale Details",
			},
			{
				name: "Delivery Available",
				slug: "delivery-available",
				type: "boolean",
				required: false,
				filterable: true,
				group: "Sale Details",
			},
		],
	},

	// ─── Top-level: Other ───
	{
		name: "Other",
		slug: "other",
		description: "Miscellaneous items and everything else",
		icon: "package",
		imageUrl:
			"https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=600&fit=crop",
		// A catch-all can hold anything, including giveaways, so nothing is
		// forced on the seller — every core field is shown but optional.
		listingForm: {
			type: "product",
			price: "optional",
			condition: "optional",
			photos: "optional",
		},
		attributes: [
			{
				name: "What Are You Listing?",
				slug: "item-type",
				type: "text",
				required: false,
				filterable: false,
			},
			{
				name: "Quantity",
				slug: "quantity",
				type: "number",
				required: false,
				filterable: false,
				min: 1,
				max: 10000,
			},
			{
				name: "Giving Away",
				slug: "free",
				type: "boolean",
				required: false,
				filterable: true,
			},
			{
				name: "Delivery Available",
				slug: "delivery-available",
				type: "boolean",
				required: false,
				filterable: true,
			},
		],
	},
];

/**
 * The `listingForm` settings above, keyed by slug — only the categories that
 * carry one. Exported so `scripts/seedListingForms.ts` can apply the very same
 * values to a database that was seeded before the field existed, instead of
 * keeping a second copy that would drift.
 */
export const categoryListingForms: Record<string, CategoryListingFormConfig> =
	Object.fromEntries(
		categoryDefinitions
			.filter((category) => category.listingForm !== undefined)
			.map((category) => [
				category.slug,
				category.listingForm as CategoryListingFormConfig,
			]),
	);

/**
 * The attribute definitions above, keyed by slug. Same reason: an existing
 * database can be topped up with the attributes it is missing without this
 * list being written down twice.
 */
export const categorySeedAttributes: Record<string, CategoryAttributeSeed[]> =
	Object.fromEntries(
		categoryDefinitions.map((category) => [category.slug, category.attributes]),
	);

async function fetchFileByURL(url: string): Promise<File> {
	const res = await fetch(url, {
		method: "GET",
	});

	if (!res.ok) {
		throw new Error(`Failed to fetch file from ${url}, status: ${res.status}`);
	}

	const data = await res.arrayBuffer();
	const filename = url.split("/").pop()?.split("?")[0] || `image-${Date.now()}`;
	const ext = filename.split(".").pop() || "jpg";

	return {
		name: `category-${filename}`,
		data: Buffer.from(data),
		mimetype: `image/${ext === "jpg" ? "jpeg" : ext}`,
		size: data.byteLength,
	};
}

export const seedCategories = async (payload: unknown) => {
	const createdCategories: Array<{ id: string; slug: string }> = [];
	const slugToId: Record<string, string> = {};

	const typedPayload = payload as {
		create: (options: {
			collection: string;
			data: Record<string, unknown>;
			file?: File;
		}) => Promise<{ id: string; slug: string }>;
		logger?: { info: (msg: string) => void; error: (msg: string) => void };
	};

	for (const catDef of categoryDefinitions) {
		const parentId = catDef.parent ? slugToId[catDef.parent] : undefined;

		// Download and create media for the category image
		let imageId: string | undefined;
		if (catDef.imageUrl) {
			try {
				const fileBuffer = await fetchFileByURL(catDef.imageUrl);
				const mediaDoc = await typedPayload.create({
					collection: "media",
					data: {
						alt: `${catDef.name} category image`,
					},
					file: fileBuffer,
				});
				imageId = mediaDoc.id;
			} catch (err) {
				typedPayload.logger?.error?.(
					`Failed to download image for ${catDef.name}: ${err}`,
				);
			}
		}

		const result = await typedPayload.create({
			collection: "categories",
			data: {
				name: catDef.name,
				slug: catDef.slug,
				description: catDef.description,
				icon: catDef.icon,
				active: true,
				parent: parentId,
				image: imageId,
				// Left undefined where the category inherits: Payload then stores
				// the field's "auto" defaults, which is exactly what inheriting
				// means to the resolver.
				listingForm: catDef.listingForm,
				attributes: catDef.attributes,
			},
		});

		slugToId[catDef.slug] = result.id;
		createdCategories.push(result);
	}

	return createdCategories;
};
