import type { OrderView } from "~/types/order";

export const NOW = new Date("2026-10-02T10:00:00.000Z");
export const LATER = "2026-10-03T10:00:00.000Z";

export function order(patch: Partial<OrderView> = {}): OrderView {
	return {
		id: "o-1",
		orderNumber: "BNS-0001",
		status: "placed",
		paymentStatus: "cod_pending",
		paymentMethod: "cod",
		amounts: {
			subtotal: 20_000,
			deliveryFee: 1_000,
			discount: 0,
			buyerProtectionFee: 0,
			total: 21_000,
			currency: "XAF",
		},
		items: [],
		timeline: [],
		shop: {
			id: "s-1",
			name: "Akwa",
			handle: "akwa",
			logoUrl: null,
			city: "douala",
			phone: null,
		},
		buyer: { id: "u-1", name: "Awa" },
		delivery: {
			method: "seller_delivery",
			recipientName: "Awa",
			phone: "+237690000000",
			phoneMasked: false,
			city: "douala",
			district: "douala.bonapriso",
			districtOther: null,
			landmark: "Derrière la pharmacie",
			gps: null,
			instructions: null,
			etaText: "24 h",
			fee: 1_000,
			pickupPoint: null,
		},
		deadlines: {
			confirmBy: LATER,
			acceptBy: LATER,
			staleAt: null,
			completeAt: null,
			withdrawalUntil: null,
			contestBy: null,
		},
		timestamps: {
			placedAt: "2026-10-02T09:00:00.000Z",
			confirmedAt: null,
			acceptedAt: null,
			shippedAt: null,
			deliveredAt: null,
			completedAt: null,
			cancelledAt: null,
			failedAt: null,
		},
		confirmation: {
			method: null,
			required: "seller_call",
			attemptsLeft: 5,
			resendsLeft: 3,
		},
		handover: {
			method: null,
			locked: false,
			attemptsLeft: 5,
			regenerationsLeft: 3,
		},
		cancellation: null,
		deliveryFailure: null,
		completionHold: "none",
		returnCaseNumber: null,
		conversationId: null,
		reviewable: false,
		...patch,
	};
}
