// Re-export Payload generated types as the base
export type {
	BoostPayment,
	Category,
	Conversation,
	Favorite,
	Listing,
	Media,
	Message,
	Report,
	Review,
	User,
} from "../../../api/src/payload-types";

import type {
	Category,
	Listing,
	Media,
	Message,
	User,
} from "../../../api/src/payload-types";

// --- Web-specific types (not generated by Payload) ---

export type ListingCondition = "new" | "like_new" | "good" | "fair" | "poor";

export type ReportReason =
	| "spam"
	| "inappropriate"
	| "fraud"
	| "prohibited"
	| "harassment"
	| "other";

export type BoostDuration = "7" | "14" | "30";

export interface CategoryAttribute {
	name: string;
	slug: string;
	type: "text" | "number" | "select" | "boolean" | "date";
	required?: boolean | null;
	filterable?: boolean | null;
	options?: { value: string; id?: string | null }[] | null;
	id?: string | null;
}

export type ListingWithDetails = Listing & {
	seller?: User;
	category?: Category;
	images?: { image: Media }[];
	isFavorite?: boolean;
};

export type CategoryWithAttributes = Category & {
	attributes?: CategoryAttribute[];
};

export interface SearchParams {
	q?: string;
	category?: string;
	minPrice?: number;
	maxPrice?: number;
	location?: string;
	limit?: number;
	offset?: number;
	attributes?: Record<string, string>;
}

export interface SearchResult {
	hits: ListingWithDetails[];
	total: number;
	limit: number;
	offset: number;
}

export interface ConversationWithDetails {
	id: string;
	participants: User[];
	listing?: Listing;
	lastMessage?: Message;
	updatedAt: string;
	createdAt: string;
}

export interface MessageWithSender {
	id: string;
	conversation: string;
	sender: User;
	content: string;
	read?: boolean | null;
	createdAt: string;
	updatedAt: string;
}

export interface UserSession {
	user: User;
	expiresAt: string;
}
