/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    listings: Listing;
    categories: Category;
    favorites: Favorite;
    conversations: Conversation;
    messages: Message;
    reviews: Review;
    reports: Report;
    'boost-payments': BoostPayment;
    'saved-searches': SavedSearch;
    'blocked-users': BlockedUser;
    tags: Tag;
    'moderation-log': ModerationLog;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    listings: ListingsSelect<false> | ListingsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    favorites: FavoritesSelect<false> | FavoritesSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    'boost-payments': BoostPaymentsSelect<false> | BoostPaymentsSelect<true>;
    'saved-searches': SavedSearchesSelect<false> | SavedSearchesSelect<true>;
    'blocked-users': BlockedUsersSelect<false> | BlockedUsersSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'moderation-log': ModerationLogSelect<false> | ModerationLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'app-settings': AppSetting;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'app-settings': AppSettingsSelect<false> | AppSettingsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      expireListings: TaskExpireListings;
      expireBoosts: TaskExpireBoosts;
      checkSearchAlerts: TaskCheckSearchAlerts;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  avatar?: (string | null) | Media;
  role: 'user' | 'moderator' | 'admin';
  authProvider: 'local' | 'google' | 'apple' | 'facebook';
  providerAccountId: string;
  authProviders?:
    | {
        provider: 'local' | 'google' | 'apple' | 'facebook';
        providerAccountId: string;
        refreshToken?: string | null;
        id?: string | null;
      }[]
    | null;
  rating?: number | null;
  totalReviews?: number | null;
  bio?: string | null;
  phone?: string | null;
  pendingPhone?: string | null;
  phoneVerifiedAt?: string | null;
  phoneVerificationCodeHash?: string | null;
  phoneVerificationExpiresAt?: string | null;
  phoneVerificationAttempts?: number | null;
  phoneVerificationLastSentAt?: string | null;
  /**
   * Free-text place shown on the public profile. Typed by the user; not derived from GPS.
   */
  location?: string | null;
  /**
   * Structured place last confirmed by the user, kept in sync with the mobile app.
   */
  homeLocation?: {
    city?: string | null;
    region?: string | null;
    country?: string | null;
    /**
     * ISO 3166-1 alpha-2, uppercase.
     */
    countryCode?: string | null;
    source?: ('device' | 'manual') | null;
    /**
     * Conflict resolution between the device copy and this one — last write wins.
     */
    updatedAt?: string | null;
  };
  verified?: boolean | null;
  /**
   * When the current suspension was applied. Empty means the account has never been suspended, or the sanction was lifted.
   */
  suspendedAt?: string | null;
  /**
   * When the suspension lifts. Empty while suspendedAt is set means the suspension is indefinite.
   */
  suspendedUntil?: string | null;
  /**
   * Shared with the suspended account.
   */
  suspendedReason?: ('spam' | 'inappropriate' | 'fraud' | 'prohibited' | 'harassment' | 'other') | null;
  /**
   * Internal. Never shown to the suspended account.
   */
  suspendedNote?: string | null;
  suspendedBy?: (string | null) | User;
  createdAt: string;
  updatedAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings".
 */
export interface Listing {
  id: string;
  title: string;
  description: string;
  price?: number | null;
  images?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  location: string;
  seller?: (string | null) | User;
  category: string | Category;
  status: 'draft' | 'pending' | 'published' | 'rejected' | 'sold' | 'expired' | 'deleted';
  boostedUntil?: string | null;
  expiresAt?: string | null;
  views?: number | null;
  attributes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  /**
   * Reason for rejection (visible to seller)
   */
  rejectionReason?: string | null;
  condition?: ('new' | 'like_new' | 'good' | 'fair' | 'poor') | null;
  tags?: (string | Tag)[] | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * Words a seller is likely to type in an ad title for this category, separated by commas — brands, slang and the other language: “voiture, bagnole, toyota, hyundai”. They are what lets the ad form guess the category from the title, and they also widen the category search. Nothing here is ever shown to buyers.
   */
  searchAliases?: string | null;
  icon?: string | null;
  image?: (string | null) | Media;
  parent?: (string | null) | Category;
  active?: boolean | null;
  /**
   * Decides which of the three built-in fields — price, condition and photos — the ad form shows for this category. Leave everything on “Inherit” to keep the current behaviour: the setting is then taken from the closest parent category that defines one.
   */
  listingForm?: {
    /**
     * Pick the closest match and the three fields below follow automatically. Set this on a top-level category and every category underneath inherits it.
     */
    type?: ('auto' | 'product' | 'service' | 'job' | 'rental' | 'generic') | null;
    /**
     * Overrides the price rule that “Kind of ad” would give. Use it for the odd category that does not fit its preset.
     */
    price?: ('auto' | 'hidden' | 'optional' | 'required') | null;
    /**
     * Whether the seller is asked how worn the item is (new, like new, good…). Hide it wherever the question makes no sense, such as a holiday rental or a plot of land.
     */
    condition?: ('auto' | 'hidden' | 'optional' | 'required') | null;
    /**
     * Whether the seller is asked for pictures. Hide it where there is nothing to photograph, such as a job offer, and choose “Optional” where a picture is welcome but not expected, such as a service. Changing this only changes what the form asks for — pictures already added to existing ads are kept.
     */
    photos?: ('auto' | 'hidden' | 'optional' | 'required') | null;
    /**
     * Wording shown above the price box, when “Price” is not the right word — for example “Loyer mensuel”, “Salaire” or “Tarif”. Leave empty for the default.
     */
    priceLabel?: string | null;
  };
  /**
   * Extra fields specific to this category. They appear in the ad form in the order listed here — drag a row to move it.
   */
  attributes?:
    | {
        name: string;
        slug: string;
        type: 'text' | 'number' | 'select' | 'boolean' | 'date';
        required?: boolean | null;
        filterable?: boolean | null;
        options?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Shown after the value, e.g. “km”, “m²”, “ch”. Leave empty when the field needs no unit.
         */
        unit?: string | null;
        /**
         * Heading this field is filed under in the form and on the ad, e.g. “Engine” or “Surface”. Fields sharing a section are shown together. Leave empty to keep it ungrouped.
         */
        group?: string | null;
        /**
         * Smallest value accepted, inclusive. Leave empty for no lower bound.
         */
        min?: number | null;
        /**
         * Largest value accepted, inclusive. Leave empty for no upper bound.
         */
        max?: number | null;
        id?: string | null;
      }[]
    | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  name: string;
  /**
   * URL-safe identifier (e.g. negotiable, delivery, urgent)
   */
  slug: string;
  /**
   * Optional emoji to display with the tag (e.g. 🤝)
   */
  emoji?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites".
 */
export interface Favorite {
  id: string;
  user?: (string | null) | User;
  listing: string | Listing;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: string;
  participants: (string | User)[];
  listing?: (string | null) | Listing;
  lastMessage?: (string | null) | Message;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: string;
  conversation: string | Conversation;
  sender: string | User;
  content: string;
  listing?: (string | null) | Listing;
  read?: boolean | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  reviewer: string | User;
  reviewedUser: string | User;
  listing?: (string | null) | Listing;
  rating: number;
  comment?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: string;
  reporter: string | User;
  targetType: 'listing' | 'user' | 'message';
  targetId: string;
  reason: 'spam' | 'inappropriate' | 'fraud' | 'prohibited' | 'harassment' | 'other';
  description?: string | null;
  status: 'pending' | 'reviewed' | 'resolved';
  resolution?: string | null;
  resolvedBy?: (string | null) | User;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boost-payments".
 */
export interface BoostPayment {
  id: string;
  listing: string | Listing;
  user: string | User;
  amount: number;
  duration: '7' | '14' | '30';
  status: 'pending' | 'completed' | 'failed' | 'refunded';
  paymentProvider: 'notchpay' | 'stripe';
  paymentReference?: string | null;
  paymentUrl?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-searches".
 */
export interface SavedSearch {
  id: string;
  user: string | User;
  name: string;
  query?: string | null;
  filters?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  url: string;
  alertEnabled?: boolean | null;
  lastCheckedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocked-users".
 */
export interface BlockedUser {
  id: string;
  blocker: string | User;
  blocked: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable history of moderation actions. Written by the moderation endpoints; cannot be edited or removed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "moderation-log".
 */
export interface ModerationLog {
  id: string;
  actor: string | User;
  actorRole: string;
  action:
    | 'listing.approve'
    | 'listing.reject'
    | 'listing.takedown'
    | 'user.suspend'
    | 'user.unsuspend'
    | 'report.resolve'
    | 'report.dismiss';
  targetType: 'listing' | 'user' | 'report';
  targetId: string;
  reason?: string | null;
  /**
   * Internal. Never surfaced to the affected account.
   */
  note?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'expireListings' | 'expireBoosts' | 'checkSearchAlerts';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'expireListings' | 'expireBoosts' | 'checkSearchAlerts') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'listings';
        value: string | Listing;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'favorites';
        value: string | Favorite;
      } | null)
    | ({
        relationTo: 'conversations';
        value: string | Conversation;
      } | null)
    | ({
        relationTo: 'messages';
        value: string | Message;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'reports';
        value: string | Report;
      } | null)
    | ({
        relationTo: 'boost-payments';
        value: string | BoostPayment;
      } | null)
    | ({
        relationTo: 'saved-searches';
        value: string | SavedSearch;
      } | null)
    | ({
        relationTo: 'blocked-users';
        value: string | BlockedUser;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'moderation-log';
        value: string | ModerationLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  role?: T;
  authProvider?: T;
  providerAccountId?: T;
  authProviders?:
    | T
    | {
        provider?: T;
        providerAccountId?: T;
        refreshToken?: T;
        id?: T;
      };
  rating?: T;
  totalReviews?: T;
  bio?: T;
  phone?: T;
  pendingPhone?: T;
  phoneVerifiedAt?: T;
  phoneVerificationCodeHash?: T;
  phoneVerificationExpiresAt?: T;
  phoneVerificationAttempts?: T;
  phoneVerificationLastSentAt?: T;
  location?: T;
  homeLocation?:
    | T
    | {
        city?: T;
        region?: T;
        country?: T;
        countryCode?: T;
        source?: T;
        updatedAt?: T;
      };
  verified?: T;
  suspendedAt?: T;
  suspendedUntil?: T;
  suspendedReason?: T;
  suspendedNote?: T;
  suspendedBy?: T;
  createdAt?: T;
  updatedAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings_select".
 */
export interface ListingsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  price?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  location?: T;
  seller?: T;
  category?: T;
  status?: T;
  boostedUntil?: T;
  expiresAt?: T;
  views?: T;
  attributes?: T;
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  rejectionReason?: T;
  condition?: T;
  tags?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  searchAliases?: T;
  icon?: T;
  image?: T;
  parent?: T;
  active?: T;
  listingForm?:
    | T
    | {
        type?: T;
        price?: T;
        condition?: T;
        photos?: T;
        priceLabel?: T;
      };
  attributes?:
    | T
    | {
        name?: T;
        slug?: T;
        type?: T;
        required?: T;
        filterable?: T;
        options?:
          | T
          | {
              value?: T;
              id?: T;
            };
        unit?: T;
        group?: T;
        min?: T;
        max?: T;
        id?: T;
      };
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites_select".
 */
export interface FavoritesSelect<T extends boolean = true> {
  user?: T;
  listing?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  participants?: T;
  listing?: T;
  lastMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  conversation?: T;
  sender?: T;
  content?: T;
  listing?: T;
  read?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  reviewer?: T;
  reviewedUser?: T;
  listing?: T;
  rating?: T;
  comment?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  reporter?: T;
  targetType?: T;
  targetId?: T;
  reason?: T;
  description?: T;
  status?: T;
  resolution?: T;
  resolvedBy?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boost-payments_select".
 */
export interface BoostPaymentsSelect<T extends boolean = true> {
  listing?: T;
  user?: T;
  amount?: T;
  duration?: T;
  status?: T;
  paymentProvider?: T;
  paymentReference?: T;
  paymentUrl?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-searches_select".
 */
export interface SavedSearchesSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  query?: T;
  filters?: T;
  url?: T;
  alertEnabled?: T;
  lastCheckedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocked-users_select".
 */
export interface BlockedUsersSelect<T extends boolean = true> {
  blocker?: T;
  blocked?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  emoji?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "moderation-log_select".
 */
export interface ModerationLogSelect<T extends boolean = true> {
  actor?: T;
  actorRole?: T;
  action?: T;
  targetType?: T;
  targetId?: T;
  reason?: T;
  note?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-settings".
 */
export interface AppSetting {
  id: string;
  auth?: {
    enabledProviders?: ('google' | 'apple' | 'facebook')[] | null;
    enableLocalAuth?: boolean | null;
  };
  sms: {
    provider: 'avlytext' | 'mtarget';
    defaultSender?: string | null;
    avlytext?: {
      apiKey?: string | null;
      sender?: string | null;
    };
    mtarget?: {
      apiKey?: string | null;
      sender?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: string;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-settings_select".
 */
export interface AppSettingsSelect<T extends boolean = true> {
  auth?:
    | T
    | {
        enabledProviders?: T;
        enableLocalAuth?: T;
      };
  sms?:
    | T
    | {
        provider?: T;
        defaultSender?: T;
        avlytext?:
          | T
          | {
              apiKey?: T;
              sender?: T;
            };
        mtarget?:
          | T
          | {
              apiKey?: T;
              sender?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskExpireListings".
 */
export interface TaskExpireListings {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskExpireBoosts".
 */
export interface TaskExpireBoosts {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCheckSearchAlerts".
 */
export interface TaskCheckSearchAlerts {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}