/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    listings: Listing;
    categories: Category;
    favorites: Favorite;
    conversations: Conversation;
    'conversation-reads': ConversationRead;
    messages: Message;
    reviews: Review;
    reports: Report;
    'boost-payments': BoostPayment;
    'payment-intents': PaymentIntent;
    'webhook-events': WebhookEvent;
    'contact-reveals': ContactReveal;
    'saved-searches': SavedSearch;
    'blocked-users': BlockedUser;
    tags: Tag;
    'moderation-log': ModerationLog;
    shops: Shop;
    'shop-members': ShopMember;
    'shop-activity-log': ShopActivityLog;
    'shop-invitations': ShopInvitation;
    products: Product;
    'product-variants': ProductVariant;
    'stock-movements': StockMovement;
    'verification-requests': VerificationRequest;
    'verification-documents': VerificationDocument;
    'verification-document-views': VerificationDocumentView;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'verification-requests': {
      documents: 'verification-documents';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    listings: ListingsSelect<false> | ListingsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    favorites: FavoritesSelect<false> | FavoritesSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    'conversation-reads': ConversationReadsSelect<false> | ConversationReadsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    'boost-payments': BoostPaymentsSelect<false> | BoostPaymentsSelect<true>;
    'payment-intents': PaymentIntentsSelect<false> | PaymentIntentsSelect<true>;
    'webhook-events': WebhookEventsSelect<false> | WebhookEventsSelect<true>;
    'contact-reveals': ContactRevealsSelect<false> | ContactRevealsSelect<true>;
    'saved-searches': SavedSearchesSelect<false> | SavedSearchesSelect<true>;
    'blocked-users': BlockedUsersSelect<false> | BlockedUsersSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'moderation-log': ModerationLogSelect<false> | ModerationLogSelect<true>;
    shops: ShopsSelect<false> | ShopsSelect<true>;
    'shop-members': ShopMembersSelect<false> | ShopMembersSelect<true>;
    'shop-activity-log': ShopActivityLogSelect<false> | ShopActivityLogSelect<true>;
    'shop-invitations': ShopInvitationsSelect<false> | ShopInvitationsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-variants': ProductVariantsSelect<false> | ProductVariantsSelect<true>;
    'stock-movements': StockMovementsSelect<false> | StockMovementsSelect<true>;
    'verification-requests': VerificationRequestsSelect<false> | VerificationRequestsSelect<true>;
    'verification-documents': VerificationDocumentsSelect<false> | VerificationDocumentsSelect<true>;
    'verification-document-views': VerificationDocumentViewsSelect<false> | VerificationDocumentViewsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'app-settings': AppSetting;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'app-settings': AppSettingsSelect<false> | AppSettingsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      expireListings: TaskExpireListings;
      expireBoosts: TaskExpireBoosts;
      checkSearchAlerts: TaskCheckSearchAlerts;
      processWebhookEvent: TaskProcessWebhookEvent;
      reconcilePendingPayments: TaskReconcilePendingPayments;
      liftExpiredShopSuspensions: TaskLiftExpiredShopSuspensions;
      processKycEvent: TaskProcessKycEvent;
      purgeVerificationData: TaskPurgeVerificationData;
      purgeShopActivity: TaskPurgeShopActivity;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  avatar?: (string | null) | Media;
  role: 'user' | 'moderator' | 'admin';
  authProvider: 'local' | 'google' | 'apple' | 'facebook';
  providerAccountId: string;
  authProviders?:
    | {
        provider: 'local' | 'google' | 'apple' | 'facebook';
        providerAccountId: string;
        refreshToken?: string | null;
        id?: string | null;
      }[]
    | null;
  rating?: number | null;
  totalReviews?: number | null;
  bio?: string | null;
  phone?: string | null;
  phoneVerified?: boolean | null;
  pendingPhone?: string | null;
  phoneVerifiedAt?: string | null;
  phoneVerificationCodeHash?: string | null;
  phoneVerificationExpiresAt?: string | null;
  phoneVerificationAttempts?: number | null;
  phoneVerificationLastSentAt?: string | null;
  /**
   * Free-text place shown on the public profile. Typed by the user; not derived from GPS.
   */
  location?: string | null;
  /**
   * Structured place last confirmed by the user, kept in sync with the mobile app.
   */
  homeLocation?: {
    city?: string | null;
    region?: string | null;
    country?: string | null;
    /**
     * ISO 3166-1 alpha-2, uppercase.
     */
    countryCode?: string | null;
    source?: ('device' | 'manual') | null;
    /**
     * Conflict resolution between the device copy and this one — last write wins.
     */
    updatedAt?: string | null;
  };
  /**
   * Derived from identityVerifiedAt. Not stored.
   */
  verified?: boolean | null;
  /**
   * Set when a level-2 request is approved, cleared on revoke or expiry. Written only by services/verification.ts.
   */
  identityVerifiedAt?: string | null;
  identityVerification?: (string | null) | VerificationRequest;
  legacyVerifiedAt?: string | null;
  /**
   * When the current suspension was applied. Empty means the account has never been suspended, or the sanction was lifted.
   */
  suspendedAt?: string | null;
  /**
   * When the suspension lifts. Empty while suspendedAt is set means the suspension is indefinite.
   */
  suspendedUntil?: string | null;
  /**
   * Shared with the suspended account.
   */
  suspendedReason?: ('spam' | 'inappropriate' | 'fraud' | 'prohibited' | 'harassment' | 'other') | null;
  /**
   * Internal. Never shown to the suspended account.
   */
  suspendedNote?: string | null;
  suspendedBy?: (string | null) | User;
  createdAt: string;
  updatedAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-requests".
 */
export interface VerificationRequest {
  id: string;
  shop: string | Shop;
  /**
   * 2 = identity, 3 = business.
   */
  requestedLevel: number;
  submittedBy: string | User;
  status: 'draft' | 'submitted' | 'in_review' | 'needs_info' | 'approved' | 'rejected' | 'revoked' | 'expired';
  statusHistory?:
    | {
        status: 'draft' | 'submitted' | 'in_review' | 'needs_info' | 'approved' | 'rejected' | 'revoked' | 'expired';
        at: string;
        actor?: (string | null) | User;
        source: 'seller' | 'reviewer' | 'vendor' | 'system';
        id?: string | null;
      }[]
    | null;
  openKey?: string | null;
  consent?: {
    acceptedAt?: string | null;
    version?: string | null;
    locale?: ('fr' | 'en') | null;
  };
  /**
   * Level 2 only. No biometric or image data is ever stored here.
   */
  kyc?: {
    provider?: ('didit' | 'smileid') | null;
    sessionRef?: string | null;
    status?: ('not_started' | 'pending' | 'approved' | 'declined' | 'review' | 'abandoned' | 'error') | null;
    attempts?: number | null;
    decidedAt?: string | null;
    documentType?: ('national_id' | 'passport' | 'residence_permit') | null;
    documentCountry?: string | null;
    documentNumberHash?: string | null;
    documentNumberLast4?: string | null;
    documentExpiresAt?: string | null;
    givenNames?: string | null;
    familyName?: string | null;
    adult?: boolean | null;
    livenessPassed?: boolean | null;
    faceMatchScore?: number | null;
    vendorWarnings?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    vendorReviewUrl?: string | null;
    vendorDataDeletedAt?: string | null;
  };
  /**
   * Level 3 only.
   */
  business?: {
    businessType?: ('entreprenant' | 'sole_trader' | 'company' | 'cooperative') | null;
    legalName?: string | null;
    tradeName?: string | null;
    rccmNumber?: string | null;
    entreprenantDeclarationNumber?: string | null;
    niu?: string | null;
    registeredAddress?: string | null;
    city?: string | null;
    legalRepresentativeName?: string | null;
    legalRepresentativeIsOwner?: boolean | null;
  };
  reviewSignals?:
    | {
        code:
          | 'identity_reused'
          | 'name_mismatch'
          | 'underage'
          | 'kyc_declined'
          | 'kyc_review'
          | 'document_reused'
          | 'rccm_reused'
          | 'niu_reused'
          | 'niu_format';
        detail?: string | null;
        relatedRequest?: (string | null) | VerificationRequest;
        id?: string | null;
      }[]
    | null;
  assignee?: (string | null) | User;
  claimedAt?: string | null;
  infoRequests?:
    | {
        reasonCode: 'document_unreadable' | 'document_missing' | 'information_inconsistent' | 'kyc_retry' | 'other';
        message: string;
        requestedBy?: (string | null) | User;
        requestedAt: string;
        respondedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  decision?: {
    decidedBy?: (string | null) | User;
    decidedAt?: string | null;
    reasonCode?: string | null;
    sellerMessage?: string | null;
    internalNote?: string | null;
    checklist?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  submittedAt?: string | null;
  approvedAt?: string | null;
  expiresAt?: string | null;
  revokedAt?: string | null;
  supersedes?: (string | null) | VerificationRequest;
  previousRequest?: (string | null) | VerificationRequest;
  documents?: {
    docs?: (string | VerificationDocument)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shops".
 */
export interface Shop {
  id: string;
  handle: string;
  previousHandles?:
    | {
        handle: string;
        until: string;
        id?: string | null;
      }[]
    | null;
  handleChangedAt?: string | null;
  name: string;
  description?: string | null;
  logo?: (string | null) | Media;
  banner?: (string | null) | Media;
  contact?: {
    phone?: string | null;
    whatsapp?: string | null;
    email?: string | null;
  };
  location?: {
    city?: string | null;
    region?: string | null;
    country?: string | null;
    countryCode?: string | null;
  };
  categories?: (string | Category)[] | null;
  owner: string | User;
  status: 'active' | 'suspended' | 'closed';
  level?: number | null;
  /**
   * Earliest expiry among the requests backing the current level. Read through shopCapabilities, which compares it at read time — never trust a job to have lowered `level` already.
   */
  levelExpiresAt?: string | null;
  /**
   * When level 2 was first reached.
   */
  verifiedAt?: string | null;
  /**
   * The expiry-notice threshold (30 or 7 days) last sent for the current levelExpiresAt, so the nightly purge fires each one once. Written only by jobs/purgeVerificationData.ts through writeShop.
   */
  notifiedExpiryDays?: number | null;
  legal?: {
    businessType?: ('entreprenant' | 'sole_trader' | 'company' | 'cooperative') | null;
    legalName?: string | null;
    rccmNumber?: string | null;
    niu?: string | null;
    verifiedAt?: string | null;
  };
  closedAt?: string | null;
  suspendedAt?: string | null;
  suspendedUntil?: string | null;
  suspendedReason?: ('spam' | 'inappropriate' | 'fraud' | 'prohibited' | 'harassment' | 'other') | null;
  suspendedNote?: string | null;
  suspendedBy?: (string | null) | User;
  suspensionLogId?: string | null;
  publishedListingCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * Words a seller is likely to type in an ad title for this category, separated by commas — brands, slang and the other language: “voiture, bagnole, toyota, hyundai”. They are what lets the ad form guess the category from the title, and they also widen the category search. Nothing here is ever shown to buyers.
   */
  searchAliases?: string | null;
  icon?: string | null;
  image?: (string | null) | Media;
  parent?: (string | null) | Category;
  active?: boolean | null;
  /**
   * Decides which of the three built-in fields — price, condition and photos — the ad form shows for this category. Leave everything on “Inherit” to keep the current behaviour: the setting is then taken from the closest parent category that defines one.
   */
  listingForm?: {
    /**
     * Pick the closest match and the three fields below follow automatically. Set this on a top-level category and every category underneath inherits it.
     */
    type?: ('auto' | 'product' | 'service' | 'job' | 'rental' | 'generic') | null;
    /**
     * Overrides the price rule that “Kind of ad” would give. Use it for the odd category that does not fit its preset.
     */
    price?: ('auto' | 'hidden' | 'optional' | 'required') | null;
    /**
     * Whether the seller is asked how worn the item is (new, like new, good…). Hide it wherever the question makes no sense, such as a holiday rental or a plot of land.
     */
    condition?: ('auto' | 'hidden' | 'optional' | 'required') | null;
    /**
     * Whether the seller is asked for pictures. Hide it where there is nothing to photograph, such as a job offer, and choose “Optional” where a picture is welcome but not expected, such as a service. Changing this only changes what the form asks for — pictures already added to existing ads are kept.
     */
    photos?: ('auto' | 'hidden' | 'optional' | 'required') | null;
    /**
     * Wording shown above the price box, when “Price” is not the right word — for example “Loyer mensuel”, “Salaire” or “Tarif”. Leave empty for the default.
     */
    priceLabel?: string | null;
  };
  /**
   * Extra fields specific to this category. They appear in the ad form in the order listed here — drag a row to move it.
   */
  attributes?:
    | {
        name: string;
        slug: string;
        type: 'text' | 'number' | 'select' | 'boolean' | 'date';
        required?: boolean | null;
        filterable?: boolean | null;
        options?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Shown after the value, e.g. “km”, “m²”, “ch”. Leave empty when the field needs no unit.
         */
        unit?: string | null;
        /**
         * Heading this field is filed under in the form and on the ad, e.g. “Engine” or “Surface”. Fields sharing a section are shown together. Leave empty to keep it ungrouped.
         */
        group?: string | null;
        /**
         * Smallest value accepted, inclusive. Leave empty for no lower bound.
         */
        min?: number | null;
        /**
         * Largest value accepted, inclusive. Leave empty for no upper bound.
         */
        max?: number | null;
        id?: string | null;
      }[]
    | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-documents".
 */
export interface VerificationDocument {
  id: string;
  request: string | VerificationRequest;
  shop: string | Shop;
  kind:
    | 'rccm_extract'
    | 'entreprenant_declaration'
    | 'niu_certificate'
    | 'legal_representative_id'
    | 'mandate'
    | 'other';
  sha256?: string | null;
  originalFilename?: string | null;
  uploadedBy?: (string | null) | User;
  duplicateOf?: (string | VerificationDocument)[] | null;
  purgedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings".
 */
export interface Listing {
  id: string;
  title: string;
  description: string;
  price?: number | null;
  images?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  location: string;
  seller?: (string | null) | User;
  category: string | Category;
  status: 'draft' | 'pending' | 'published' | 'rejected' | 'sold' | 'expired' | 'deleted';
  boostedUntil?: string | null;
  expiresAt?: string | null;
  views?: number | null;
  attributes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  /**
   * Reason for rejection (visible to seller)
   */
  rejectionReason?: string | null;
  condition?: ('new' | 'like_new' | 'good' | 'fair' | 'poor') | null;
  tags?: (string | Tag)[] | null;
  shop?: (string | null) | Shop;
  product?: (string | null) | Product;
  /**
   * Derived from the product's variants by the product service.
   */
  productSummary?: {
    priceMin?: number | null;
    priceMax?: number | null;
    /**
     * Buyer-safe purchasability signal, not a unit count — the exact aggregate stays on the privileged catalogue view only.
     */
    available?: boolean | null;
    variantCount?: number | null;
    trackInventory?: boolean | null;
  };
  /**
   * Set when a moderator takes this listing down and chooses not to restore it. Blocks the product service from republishing it on an ordinary sync (a stock movement, a product edit) until a moderator clears it.
   */
  moderationHold?: boolean | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  name: string;
  /**
   * URL-safe identifier (e.g. negotiable, delivery, urgent)
   */
  slug: string;
  /**
   * Optional emoji to display with the tag (e.g. 🤝)
   */
  emoji?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  shop: string | Shop;
  title: string;
  description?: string | null;
  category: string | Category;
  condition?: ('new' | 'like_new' | 'good' | 'fair' | 'poor') | null;
  attributes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  images?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'active' | 'archived';
  options?:
    | {
        name: string;
        values: string[];
        id?: string | null;
      }[]
    | null;
  delivery?: {
    handlingHours?: number | null;
    weightGrams?: number | null;
    codAllowed?: boolean | null;
    pickupAllowed?: boolean | null;
  };
  returnPolicy?: string | null;
  /**
   * The published listing, written by the product service.
   */
  listing?: (string | null) | Listing;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites".
 */
export interface Favorite {
  id: string;
  user?: (string | null) | User;
  listing: string | Listing;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: string;
  participants: (string | User)[];
  listing?: (string | null) | Listing;
  lastMessage?: (string | null) | Message;
  shop?: (string | null) | Shop;
  buyer?: (string | null) | User;
  assignee?: (string | null) | User;
  assignedAt?: string | null;
  assignedBy?: (string | null) | User;
  inboxStatus?: ('open' | 'done') | null;
  lastMessageAt?: string | null;
  awaitingReply?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: string;
  conversation: string | Conversation;
  sender: string | User;
  content: string;
  listing?: (string | null) | Listing;
  read?: boolean | null;
  /**
   * Set on shop conversations only; absent on a classic one.
   */
  senderSide?: ('buyer' | 'shop') | null;
  /**
   * The author deleted their account; the message is re-attributed to the shop owner and shown as "Former member".
   */
  formerMemberAuthor?: boolean | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversation-reads".
 */
export interface ConversationRead {
  id: string;
  conversation: string | Conversation;
  user: string | User;
  lastReadAt?: string | null;
  lastReadMessage?: (string | null) | Message;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  reviewer: string | User;
  reviewedUser: string | User;
  listing?: (string | null) | Listing;
  rating: number;
  comment?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: string;
  reporter: string | User;
  targetType: 'listing' | 'user' | 'message' | 'shop';
  targetId: string;
  reason: 'spam' | 'inappropriate' | 'fraud' | 'prohibited' | 'harassment' | 'other';
  description?: string | null;
  status: 'pending' | 'reviewed' | 'resolved';
  resolution?: string | null;
  resolvedBy?: (string | null) | User;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boost-payments".
 */
export interface BoostPayment {
  id: string;
  listing: string | Listing;
  user?: (string | null) | User;
  amount: number;
  duration: '7' | '14' | '30';
  status: 'pending' | 'completed' | 'failed' | 'refunded';
  paymentProvider: 'notchpay' | 'stripe';
  paymentReference?: string | null;
  paymentUrl?: string | null;
  boostedUntil?: string | null;
  paymentIntent?: (string | null) | PaymentIntent;
  customerDeletedAt?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-intents".
 */
export interface PaymentIntent {
  id: string;
  purpose: 'boost';
  targetType: 'boost-payment';
  targetId: string;
  customer?: (string | null) | User;
  customerDeletedAt?: string | null;
  amount: number;
  currency: string;
  provider: 'notchpay' | 'stripe';
  providerReference?: string | null;
  reference?: string | null;
  status: 'created' | 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired';
  statusHistory?:
    | {
        status: 'created' | 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired';
        source: 'webhook' | 'callback' | 'reconcile' | 'system';
        at: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  idempotencyKey: string;
  checkoutUrl?: string | null;
  expiresAt?: string | null;
  settledAmount?: number | null;
  settledCurrency?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-events".
 */
export interface WebhookEvent {
  id: string;
  provider: 'notchpay' | 'stripe' | 'didit' | 'smileid';
  providerEventId: string;
  type?: string | null;
  reference?: string | null;
  providerReference?: string | null;
  payloadHash: string;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  receivedAt: string;
  processedAt?: string | null;
  attempts?: number | null;
  lastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-reveals".
 */
export interface ContactReveal {
  id: string;
  listing: string | Listing;
  seller: string | User;
  viewer: string | User;
  revealWindow: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-searches".
 */
export interface SavedSearch {
  id: string;
  user: string | User;
  name: string;
  query?: string | null;
  filters?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  url: string;
  alertEnabled?: boolean | null;
  lastCheckedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocked-users".
 */
export interface BlockedUser {
  id: string;
  blocker: string | User;
  blocked: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable history of moderation actions. Written by the moderation endpoints; cannot be edited or removed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "moderation-log".
 */
export interface ModerationLog {
  id: string;
  actor?: (string | null) | User;
  actorRole: string;
  action:
    | 'listing.approve'
    | 'listing.reject'
    | 'listing.takedown'
    | 'listing.holdRelease'
    | 'user.suspend'
    | 'user.unsuspend'
    | 'shop.suspend'
    | 'shop.unsuspend'
    | 'report.resolve'
    | 'report.dismiss'
    | 'verification.claim'
    | 'verification.release'
    | 'verification.request_info'
    | 'verification.approve'
    | 'verification.reject'
    | 'verification.revoke'
    | 'verification.expire';
  targetType: 'listing' | 'user' | 'report' | 'shop' | 'verification-request';
  targetId: string;
  reason?: string | null;
  /**
   * Internal. Never surfaced to the affected account.
   */
  note?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-members".
 */
export interface ShopMember {
  id: string;
  shop: string | Shop;
  user: string | User;
  role: 'owner' | 'manager' | 'staff';
  status: 'active' | 'revoked';
  /**
   * The invitation that created or reactivated this row; empty for the owner.
   */
  invitation?: (string | null) | ShopInvitation;
  joinedAt?: string | null;
  revokedAt?: string | null;
  /**
   * Empty for a system revocation.
   */
  revokedBy?: (string | null) | User;
  revokedReason?: ('removed' | 'left' | 'shop_closed' | 'account_deleted') | null;
  inboxNotifications: 'all' | 'assigned' | 'none';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-invitations".
 */
export interface ShopInvitation {
  id: string;
  shop: string | Shop;
  role: 'manager' | 'staff';
  channel: 'phone' | 'email';
  phone?: string | null;
  email?: string | null;
  pendingKey?: string | null;
  tokenHash: string;
  status: 'pending' | 'accepted' | 'declined' | 'revoked' | 'expired';
  invitedBy: string | User;
  expiresAt: string;
  sendCount: number;
  lastSentAt?: string | null;
  acceptedBy?: (string | null) | User;
  respondedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-activity-log".
 */
export interface ShopActivityLog {
  id: string;
  shop: string | Shop;
  actor?: (string | null) | User;
  /**
   * Snapshot at the time of the action: owner, manager, staff or system.
   */
  actorRole: string;
  action:
    | 'member.invited'
    | 'member.invitation_resent'
    | 'member.invitation_revoked'
    | 'member.joined'
    | 'member.role_changed'
    | 'member.removed'
    | 'member.left'
    | 'member.paused'
    | 'member.resumed'
    | 'product.created'
    | 'product.updated'
    | 'product.published'
    | 'product.archived'
    | 'variant.price_changed'
    | 'variant.cost_changed'
    | 'stock.moved'
    | 'listing.attached'
    | 'listing.detached'
    | 'shop.updated'
    | 'shop.handle_changed'
    | 'shop.closed'
    | 'conversation.assigned'
    | 'conversation.status_changed'
    | 'verification.submitted';
  targetType:
    | 'shop'
    | 'member'
    | 'invitation'
    | 'product'
    | 'variant'
    | 'listing'
    | 'conversation'
    | 'verification-request';
  targetId: string;
  /**
   * Before and after values of the changed fields. Cost values only on variant.cost_changed.
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants".
 */
export interface ProductVariant {
  id: string;
  product: string | Product;
  shop: string | Shop;
  optionValues?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sku?: string | null;
  price: number;
  cost?: number | null;
  trackInventory?: boolean | null;
  stockOnHand?: number | null;
  stockReserved?: number | null;
  lowStockThreshold?: number | null;
  /**
   * Buyer-safe purchasability signal: true when the variant can be bought right now.
   */
  available?: boolean | null;
  /**
   * Set when the variant is removed from its product; movements are kept.
   */
  archivedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements".
 */
export interface StockMovement {
  id: string;
  variant: string | ProductVariant;
  product?: (string | null) | Product;
  shop: string | Shop;
  type: 'receipt' | 'adjustment' | 'loss' | 'return' | 'sale' | 'reservation' | 'release';
  quantity: number;
  unitCost?: number | null;
  stockAfter: number;
  note?: string | null;
  actor?: (string | null) | User;
  orderRef?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-document-views".
 */
export interface VerificationDocumentView {
  id: string;
  document: string | VerificationDocument;
  request: string | VerificationRequest;
  viewer: string | User;
  viewerRole?: string | null;
  ipHash?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'expireListings'
          | 'expireBoosts'
          | 'checkSearchAlerts'
          | 'processWebhookEvent'
          | 'reconcilePendingPayments'
          | 'liftExpiredShopSuspensions'
          | 'processKycEvent'
          | 'purgeVerificationData'
          | 'purgeShopActivity';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | (
        | 'inline'
        | 'expireListings'
        | 'expireBoosts'
        | 'checkSearchAlerts'
        | 'processWebhookEvent'
        | 'reconcilePendingPayments'
        | 'liftExpiredShopSuspensions'
        | 'processKycEvent'
        | 'purgeVerificationData'
        | 'purgeShopActivity'
      )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'listings';
        value: string | Listing;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'favorites';
        value: string | Favorite;
      } | null)
    | ({
        relationTo: 'conversations';
        value: string | Conversation;
      } | null)
    | ({
        relationTo: 'conversation-reads';
        value: string | ConversationRead;
      } | null)
    | ({
        relationTo: 'messages';
        value: string | Message;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'reports';
        value: string | Report;
      } | null)
    | ({
        relationTo: 'boost-payments';
        value: string | BoostPayment;
      } | null)
    | ({
        relationTo: 'payment-intents';
        value: string | PaymentIntent;
      } | null)
    | ({
        relationTo: 'webhook-events';
        value: string | WebhookEvent;
      } | null)
    | ({
        relationTo: 'contact-reveals';
        value: string | ContactReveal;
      } | null)
    | ({
        relationTo: 'saved-searches';
        value: string | SavedSearch;
      } | null)
    | ({
        relationTo: 'blocked-users';
        value: string | BlockedUser;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'moderation-log';
        value: string | ModerationLog;
      } | null)
    | ({
        relationTo: 'shops';
        value: string | Shop;
      } | null)
    | ({
        relationTo: 'shop-members';
        value: string | ShopMember;
      } | null)
    | ({
        relationTo: 'shop-activity-log';
        value: string | ShopActivityLog;
      } | null)
    | ({
        relationTo: 'shop-invitations';
        value: string | ShopInvitation;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'product-variants';
        value: string | ProductVariant;
      } | null)
    | ({
        relationTo: 'stock-movements';
        value: string | StockMovement;
      } | null)
    | ({
        relationTo: 'verification-requests';
        value: string | VerificationRequest;
      } | null)
    | ({
        relationTo: 'verification-documents';
        value: string | VerificationDocument;
      } | null)
    | ({
        relationTo: 'verification-document-views';
        value: string | VerificationDocumentView;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  role?: T;
  authProvider?: T;
  providerAccountId?: T;
  authProviders?:
    | T
    | {
        provider?: T;
        providerAccountId?: T;
        refreshToken?: T;
        id?: T;
      };
  rating?: T;
  totalReviews?: T;
  bio?: T;
  phone?: T;
  phoneVerified?: T;
  pendingPhone?: T;
  phoneVerifiedAt?: T;
  phoneVerificationCodeHash?: T;
  phoneVerificationExpiresAt?: T;
  phoneVerificationAttempts?: T;
  phoneVerificationLastSentAt?: T;
  location?: T;
  homeLocation?:
    | T
    | {
        city?: T;
        region?: T;
        country?: T;
        countryCode?: T;
        source?: T;
        updatedAt?: T;
      };
  verified?: T;
  identityVerifiedAt?: T;
  identityVerification?: T;
  legacyVerifiedAt?: T;
  suspendedAt?: T;
  suspendedUntil?: T;
  suspendedReason?: T;
  suspendedNote?: T;
  suspendedBy?: T;
  createdAt?: T;
  updatedAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings_select".
 */
export interface ListingsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  price?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  location?: T;
  seller?: T;
  category?: T;
  status?: T;
  boostedUntil?: T;
  expiresAt?: T;
  views?: T;
  attributes?: T;
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  rejectionReason?: T;
  condition?: T;
  tags?: T;
  shop?: T;
  product?: T;
  productSummary?:
    | T
    | {
        priceMin?: T;
        priceMax?: T;
        available?: T;
        variantCount?: T;
        trackInventory?: T;
      };
  moderationHold?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  searchAliases?: T;
  icon?: T;
  image?: T;
  parent?: T;
  active?: T;
  listingForm?:
    | T
    | {
        type?: T;
        price?: T;
        condition?: T;
        photos?: T;
        priceLabel?: T;
      };
  attributes?:
    | T
    | {
        name?: T;
        slug?: T;
        type?: T;
        required?: T;
        filterable?: T;
        options?:
          | T
          | {
              value?: T;
              id?: T;
            };
        unit?: T;
        group?: T;
        min?: T;
        max?: T;
        id?: T;
      };
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites_select".
 */
export interface FavoritesSelect<T extends boolean = true> {
  user?: T;
  listing?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  participants?: T;
  listing?: T;
  lastMessage?: T;
  shop?: T;
  buyer?: T;
  assignee?: T;
  assignedAt?: T;
  assignedBy?: T;
  inboxStatus?: T;
  lastMessageAt?: T;
  awaitingReply?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversation-reads_select".
 */
export interface ConversationReadsSelect<T extends boolean = true> {
  conversation?: T;
  user?: T;
  lastReadAt?: T;
  lastReadMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  conversation?: T;
  sender?: T;
  content?: T;
  listing?: T;
  read?: T;
  senderSide?: T;
  formerMemberAuthor?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  reviewer?: T;
  reviewedUser?: T;
  listing?: T;
  rating?: T;
  comment?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  reporter?: T;
  targetType?: T;
  targetId?: T;
  reason?: T;
  description?: T;
  status?: T;
  resolution?: T;
  resolvedBy?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boost-payments_select".
 */
export interface BoostPaymentsSelect<T extends boolean = true> {
  listing?: T;
  user?: T;
  amount?: T;
  duration?: T;
  status?: T;
  paymentProvider?: T;
  paymentReference?: T;
  paymentUrl?: T;
  boostedUntil?: T;
  paymentIntent?: T;
  customerDeletedAt?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-intents_select".
 */
export interface PaymentIntentsSelect<T extends boolean = true> {
  purpose?: T;
  targetType?: T;
  targetId?: T;
  customer?: T;
  customerDeletedAt?: T;
  amount?: T;
  currency?: T;
  provider?: T;
  providerReference?: T;
  reference?: T;
  status?: T;
  statusHistory?:
    | T
    | {
        status?: T;
        source?: T;
        at?: T;
        note?: T;
        id?: T;
      };
  idempotencyKey?: T;
  checkoutUrl?: T;
  expiresAt?: T;
  settledAmount?: T;
  settledCurrency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-events_select".
 */
export interface WebhookEventsSelect<T extends boolean = true> {
  provider?: T;
  providerEventId?: T;
  type?: T;
  reference?: T;
  providerReference?: T;
  payloadHash?: T;
  raw?: T;
  receivedAt?: T;
  processedAt?: T;
  attempts?: T;
  lastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-reveals_select".
 */
export interface ContactRevealsSelect<T extends boolean = true> {
  listing?: T;
  seller?: T;
  viewer?: T;
  revealWindow?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-searches_select".
 */
export interface SavedSearchesSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  query?: T;
  filters?: T;
  url?: T;
  alertEnabled?: T;
  lastCheckedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocked-users_select".
 */
export interface BlockedUsersSelect<T extends boolean = true> {
  blocker?: T;
  blocked?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  emoji?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "moderation-log_select".
 */
export interface ModerationLogSelect<T extends boolean = true> {
  actor?: T;
  actorRole?: T;
  action?: T;
  targetType?: T;
  targetId?: T;
  reason?: T;
  note?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shops_select".
 */
export interface ShopsSelect<T extends boolean = true> {
  handle?: T;
  previousHandles?:
    | T
    | {
        handle?: T;
        until?: T;
        id?: T;
      };
  handleChangedAt?: T;
  name?: T;
  description?: T;
  logo?: T;
  banner?: T;
  contact?:
    | T
    | {
        phone?: T;
        whatsapp?: T;
        email?: T;
      };
  location?:
    | T
    | {
        city?: T;
        region?: T;
        country?: T;
        countryCode?: T;
      };
  categories?: T;
  owner?: T;
  status?: T;
  level?: T;
  levelExpiresAt?: T;
  verifiedAt?: T;
  notifiedExpiryDays?: T;
  legal?:
    | T
    | {
        businessType?: T;
        legalName?: T;
        rccmNumber?: T;
        niu?: T;
        verifiedAt?: T;
      };
  closedAt?: T;
  suspendedAt?: T;
  suspendedUntil?: T;
  suspendedReason?: T;
  suspendedNote?: T;
  suspendedBy?: T;
  suspensionLogId?: T;
  publishedListingCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-members_select".
 */
export interface ShopMembersSelect<T extends boolean = true> {
  shop?: T;
  user?: T;
  role?: T;
  status?: T;
  invitation?: T;
  joinedAt?: T;
  revokedAt?: T;
  revokedBy?: T;
  revokedReason?: T;
  inboxNotifications?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-activity-log_select".
 */
export interface ShopActivityLogSelect<T extends boolean = true> {
  shop?: T;
  actor?: T;
  actorRole?: T;
  action?: T;
  targetType?: T;
  targetId?: T;
  metadata?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-invitations_select".
 */
export interface ShopInvitationsSelect<T extends boolean = true> {
  shop?: T;
  role?: T;
  channel?: T;
  phone?: T;
  email?: T;
  pendingKey?: T;
  tokenHash?: T;
  status?: T;
  invitedBy?: T;
  expiresAt?: T;
  sendCount?: T;
  lastSentAt?: T;
  acceptedBy?: T;
  respondedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  shop?: T;
  title?: T;
  description?: T;
  category?: T;
  condition?: T;
  attributes?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  status?: T;
  options?:
    | T
    | {
        name?: T;
        values?: T;
        id?: T;
      };
  delivery?:
    | T
    | {
        handlingHours?: T;
        weightGrams?: T;
        codAllowed?: T;
        pickupAllowed?: T;
      };
  returnPolicy?: T;
  listing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants_select".
 */
export interface ProductVariantsSelect<T extends boolean = true> {
  product?: T;
  shop?: T;
  optionValues?: T;
  sku?: T;
  price?: T;
  cost?: T;
  trackInventory?: T;
  stockOnHand?: T;
  stockReserved?: T;
  lowStockThreshold?: T;
  available?: T;
  archivedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements_select".
 */
export interface StockMovementsSelect<T extends boolean = true> {
  variant?: T;
  product?: T;
  shop?: T;
  type?: T;
  quantity?: T;
  unitCost?: T;
  stockAfter?: T;
  note?: T;
  actor?: T;
  orderRef?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-requests_select".
 */
export interface VerificationRequestsSelect<T extends boolean = true> {
  shop?: T;
  requestedLevel?: T;
  submittedBy?: T;
  status?: T;
  statusHistory?:
    | T
    | {
        status?: T;
        at?: T;
        actor?: T;
        source?: T;
        id?: T;
      };
  openKey?: T;
  consent?:
    | T
    | {
        acceptedAt?: T;
        version?: T;
        locale?: T;
      };
  kyc?:
    | T
    | {
        provider?: T;
        sessionRef?: T;
        status?: T;
        attempts?: T;
        decidedAt?: T;
        documentType?: T;
        documentCountry?: T;
        documentNumberHash?: T;
        documentNumberLast4?: T;
        documentExpiresAt?: T;
        givenNames?: T;
        familyName?: T;
        adult?: T;
        livenessPassed?: T;
        faceMatchScore?: T;
        vendorWarnings?: T;
        vendorReviewUrl?: T;
        vendorDataDeletedAt?: T;
      };
  business?:
    | T
    | {
        businessType?: T;
        legalName?: T;
        tradeName?: T;
        rccmNumber?: T;
        entreprenantDeclarationNumber?: T;
        niu?: T;
        registeredAddress?: T;
        city?: T;
        legalRepresentativeName?: T;
        legalRepresentativeIsOwner?: T;
      };
  reviewSignals?:
    | T
    | {
        code?: T;
        detail?: T;
        relatedRequest?: T;
        id?: T;
      };
  assignee?: T;
  claimedAt?: T;
  infoRequests?:
    | T
    | {
        reasonCode?: T;
        message?: T;
        requestedBy?: T;
        requestedAt?: T;
        respondedAt?: T;
        id?: T;
      };
  decision?:
    | T
    | {
        decidedBy?: T;
        decidedAt?: T;
        reasonCode?: T;
        sellerMessage?: T;
        internalNote?: T;
        checklist?: T;
      };
  submittedAt?: T;
  approvedAt?: T;
  expiresAt?: T;
  revokedAt?: T;
  supersedes?: T;
  previousRequest?: T;
  documents?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-documents_select".
 */
export interface VerificationDocumentsSelect<T extends boolean = true> {
  request?: T;
  shop?: T;
  kind?: T;
  sha256?: T;
  originalFilename?: T;
  uploadedBy?: T;
  duplicateOf?: T;
  purgedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?: T | {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-document-views_select".
 */
export interface VerificationDocumentViewsSelect<T extends boolean = true> {
  document?: T;
  request?: T;
  viewer?: T;
  viewerRole?: T;
  ipHash?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-settings".
 */
export interface AppSetting {
  id: string;
  auth?: {
    enabledProviders?: ('google' | 'apple' | 'facebook')[] | null;
    enableLocalAuth?: boolean | null;
  };
  sms: {
    provider: 'avlytext' | 'mtarget' | 'console';
    defaultSender?: string | null;
    avlytext?: {
      apiKey?: string | null;
      sender?: string | null;
    };
    mtarget?: {
      apiKey?: string | null;
      sender?: string | null;
    };
  };
  shops?: {
    /**
     * Off: clients hide shop entry points and POST /api/shops returns shop.disabled. Existing shop pages keep resolving.
     */
    enabled?: boolean | null;
    maxPerUser?: number | null;
  };
  verification: {
    /**
     * Off: clients hide verification entry points and the seller write routes return verification.disabled. Existing requests stay readable, reviewers keep deciding, and the retention job keeps running.
     */
    enabled?: boolean | null;
    kycProvider: 'didit' | 'smileid';
    /**
     * Off at launch: every identity decision is taken by a person. On, a level-2 request the vendor approved with no review signal is approved automatically.
     */
    autoApproveIdentity?: boolean | null;
    /**
     * Recorded in the processing register. Verification cannot be enabled until all four are set.
     */
    authorisation?: {
      reference?: string | null;
      grantedAt?: string | null;
      transfersAuthorised?: boolean | null;
      /**
       * The consent text version the clients must send back, e.g. "kyc-2026-10-v1".
       */
      consentVersion?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: string;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-settings_select".
 */
export interface AppSettingsSelect<T extends boolean = true> {
  auth?:
    | T
    | {
        enabledProviders?: T;
        enableLocalAuth?: T;
      };
  sms?:
    | T
    | {
        provider?: T;
        defaultSender?: T;
        avlytext?:
          | T
          | {
              apiKey?: T;
              sender?: T;
            };
        mtarget?:
          | T
          | {
              apiKey?: T;
              sender?: T;
            };
      };
  shops?:
    | T
    | {
        enabled?: T;
        maxPerUser?: T;
      };
  verification?:
    | T
    | {
        enabled?: T;
        kycProvider?: T;
        autoApproveIdentity?: T;
        authorisation?:
          | T
          | {
              reference?: T;
              grantedAt?: T;
              transfersAuthorised?: T;
              consentVersion?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskExpireListings".
 */
export interface TaskExpireListings {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskExpireBoosts".
 */
export interface TaskExpireBoosts {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCheckSearchAlerts".
 */
export interface TaskCheckSearchAlerts {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskProcessWebhookEvent".
 */
export interface TaskProcessWebhookEvent {
  input: {
    eventId: string;
  };
  output: {
    outcome?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskReconcilePendingPayments".
 */
export interface TaskReconcilePendingPayments {
  input?: unknown;
  output: {
    checked?: number | null;
    settled?: number | null;
    expired?: number | null;
    errors?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskLiftExpiredShopSuspensions".
 */
export interface TaskLiftExpiredShopSuspensions {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskProcessKycEvent".
 */
export interface TaskProcessKycEvent {
  input: {
    webhookEventId: string;
    provider: string;
    sessionRef: string;
  };
  output: {
    handled?: boolean | null;
    requestId?: string | null;
    status?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskPurgeVerificationData".
 */
export interface TaskPurgeVerificationData {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskPurgeShopActivity".
 */
export interface TaskPurgeShopActivity {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}